"""Public use-case API of the Sites module."""

from .ai_badge import badge_visible
from .block_contracts import (
    InvalidSiteBlockData,
    UnknownSiteBlockType,
    UnknownSiteBlockVersion,
    validate_site_block,
)
from .page_templates import PageTemplate, PageTemplateNotFound, page_template_catalog
from .services import (
    DraftVersionConflict,
    MutationResult,
    PageDraft,
    PageKeyConflict,
    PageNotFound,
    PageTranslations,
    PageVersionNotFound,
    SiteMediaReferenceUnavailable,
    SiteNotFound,
    SitePublication,
    SitePublicationConflict,
    SitePublicationNotReady,
    SitesIdempotencyConflict,
    SiteSlugConflict,
    TranslationFallbackConflict,
    TranslationSlugConflict,
    TranslationSlugLocked,
    TranslationVersionConflict,
    UnsupportedSiteLocale,
    create_page,
    create_site,
    get_draft,
    get_draft_preview,
    get_site_localization_report,
    import_page_template,
    list_page_translations,
    list_pages,
    list_sites,
    publish_site,
    read_site_audit_target,
    save_draft,
    save_page_translation,
)

__all__ = [
    "badge_visible",
    "DraftVersionConflict",
    "InvalidSiteBlockData",
    "MutationResult",
    "PageDraft",
    "PageKeyConflict",
    "PageNotFound",
    "PageTemplate",
    "PageTemplateNotFound",
    "PageVersionNotFound",
    "PageTranslations",
    "SiteNotFound",
    "SiteMediaReferenceUnavailable",
    "SitePublication",
    "SitePublicationConflict",
    "SitePublicationNotReady",
    "SiteSlugConflict",
    "SitesIdempotencyConflict",
    "TranslationFallbackConflict",
    "TranslationSlugConflict",
    "TranslationSlugLocked",
    "TranslationVersionConflict",
    "UnknownSiteBlockType",
    "UnknownSiteBlockVersion",
    "UnsupportedSiteLocale",
    "create_page",
    "create_site",
    "get_draft",
    "get_draft_preview",
    "get_site_localization_report",
    "import_page_template",
    "list_page_translations",
    "list_pages",
    "list_sites",
    "page_template_catalog",
    "publish_site",
    "read_site_audit_target",
    "save_draft",
    "save_page_translation",
    "validate_site_block",
]
