from django.urls import path

from .collection_views import (
    ContentCollectionListCreateView,
    ContentCollectionNavigationView,
    ContentCollectionPolicyView,
    ContentEntryDraftView,
    ContentEntryListCreateView,
    ContentEntryPublicationView,
    ContentEntryTranslationView,
    EntryScheduleView,
    EntryTagsView,
    PageAutomationPolicyView,
)
from .domain_views import (
    SiteDomainActionView,
    SiteDomainListCreateView,
    SitePlatformDomainView,
)
from .onboarding_views import (
    SiteOnboardingCompleteView,
    SiteOnboardingView,
    SubdomainAvailabilityView,
)
from .views import (
    AutomationConnectionListView,
    AutomationGrantRevokeView,
    ChangeSetApplyView,
    ChangeSetProposalView,
    ContentCapabilitiesView,
    ContentInventoryView,
    ContentProposalDetailView,
    ContentProposalDiscardView,
    ContentProposalListView,
    OperationStatusView,
    PageDraftPreviewView,
    PageDraftView,
    PageListCreateView,
    PageTemplateImportView,
    PageTranslationListView,
    PageTranslationView,
    PageTypeView,
    PageUrlView,
    SiteListCreateView,
    SiteLocalizationReportView,
    SiteNavigationView,
    SitePublicationCreateView,
    SitePublicationRollbackView,
    SitePurposeView,
    SiteRedirectListView,
    SiteRedirectView,
)

app_name = "sites"

urlpatterns = [
    path(
        "pages/<uuid:page_id>/url/",
        PageUrlView.as_view(),
        name="page-url",
    ),
    path(
        "redirects/<uuid:redirect_id>/",
        SiteRedirectView.as_view(),
        name="redirect-detail",
    ),
    path(
        "<uuid:site_id>/redirects/",
        SiteRedirectListView.as_view(),
        name="site-redirects",
    ),
    path(
        "pages/<uuid:page_id>/type/",
        PageTypeView.as_view(),
        name="page-type",
    ),
    path(
        "<uuid:site_id>/purpose/",
        SitePurposeView.as_view(),
        name="site-purpose",
    ),
    path(
        "operations/<str:idempotency_key>/",
        OperationStatusView.as_view(),
        name="operation-status",
    ),
    path(
        "connections/",
        AutomationConnectionListView.as_view(),
        name="automation-connections",
    ),
    path(
        "connections/<uuid:grant_id>/revoke/",
        AutomationGrantRevokeView.as_view(),
        name="automation-grant-revoke",
    ),
    path("proposals/", ContentProposalListView.as_view(), name="content-proposals"),
    path(
        "proposals/<uuid:proposal_id>/",
        ContentProposalDetailView.as_view(),
        name="content-proposal-detail",
    ),
    path(
        "proposals/<uuid:proposal_id>/discard/",
        ContentProposalDiscardView.as_view(),
        name="content-proposal-discard",
    ),
    path("inventory/", ContentInventoryView.as_view(), name="content-inventory"),
    path("changes/", ChangeSetProposalView.as_view(), name="change-set-preview"),
    path(
        "changes/apply/",
        ChangeSetApplyView.as_view(),
        name="change-set-apply",
    ),
    path(
        "capabilities/",
        ContentCapabilitiesView.as_view(),
        name="content-capabilities",
    ),
    path(
        "subdomain-availability/",
        SubdomainAvailabilityView.as_view(),
        name="subdomain-availability",
    ),
    path("onboarding/", SiteOnboardingView.as_view(), name="onboarding"),
    path(
        "onboarding/complete/",
        SiteOnboardingCompleteView.as_view(),
        name="onboarding-complete",
    ),
    path(
        "<uuid:site_id>/domains/",
        SiteDomainListCreateView.as_view(),
        name="site-domain-list-create",
    ),
    path(
        "domains/<uuid:domain_id>/actions/",
        SiteDomainActionView.as_view(),
        name="site-domain-action",
    ),
    path(
        "<uuid:site_id>/platform-domain/",
        SitePlatformDomainView.as_view(),
        name="platform-domain-change",
    ),
    path("", SiteListCreateView.as_view(), name="list-create"),
    path("<uuid:site_id>/pages/", PageListCreateView.as_view(), name="page-list-create"),
    path(
        "<uuid:site_id>/localization/",
        SiteLocalizationReportView.as_view(),
        name="localization-report",
    ),
    path(
        "<uuid:site_id>/collections/",
        ContentCollectionListCreateView.as_view(),
        name="collection-list-create",
    ),
    path(
        "collections/<uuid:collection_id>/entries/",
        ContentEntryListCreateView.as_view(),
        name="entry-list-create",
    ),
    path(
        "collections/<uuid:collection_id>/navigation/",
        ContentCollectionNavigationView.as_view(),
        name="collection-navigation",
    ),
    path(
        "collections/<uuid:collection_id>/policy/",
        ContentCollectionPolicyView.as_view(),
        name="collection-policy",
    ),
    path(
        "pages/<uuid:page_id>/policy/",
        PageAutomationPolicyView.as_view(),
        name="page-policy",
    ),
    path(
        "entries/<uuid:entry_id>/draft/",
        ContentEntryDraftView.as_view(),
        name="entry-draft",
    ),
    path(
        "entries/<uuid:entry_id>/translations/",
        ContentEntryTranslationView.as_view(),
        name="entry-translations",
    ),
    path(
        "entries/<uuid:entry_id>/tags/",
        EntryTagsView.as_view(),
        name="entry-tags",
    ),
    path(
        "entries/<uuid:entry_id>/schedule/",
        EntryScheduleView.as_view(),
        name="entry-schedule",
    ),
    path(
        "entries/<uuid:entry_id>/publication/",
        ContentEntryPublicationView.as_view(),
        name="entry-publication",
    ),
    path(
        "<uuid:site_id>/navigation/",
        SiteNavigationView.as_view(),
        name="navigation",
    ),
    path(
        "<uuid:site_id>/publications/",
        SitePublicationCreateView.as_view(),
        name="publication-create",
    ),
    path(
        "<uuid:site_id>/publications/<uuid:publication_id>/rollback/",
        SitePublicationRollbackView.as_view(),
        name="publication-rollback",
    ),
    path("pages/<uuid:page_id>/draft/", PageDraftView.as_view(), name="page-draft"),
    path(
        "pages/<uuid:page_id>/template-import/",
        PageTemplateImportView.as_view(),
        name="page-template-import",
    ),
    path(
        "pages/<uuid:page_id>/preview/<uuid:version_id>/",
        PageDraftPreviewView.as_view(),
        name="page-draft-preview",
    ),
    path(
        "pages/<uuid:page_id>/translations/",
        PageTranslationListView.as_view(),
        name="page-translation-list",
    ),
    path(
        "pages/<uuid:page_id>/translations/<str:locale>/",
        PageTranslationView.as_view(),
        name="page-translation",
    ),
]
