# Generated by Django 5.2.17 on 2026-08-11 17:02

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

ENABLE_MEDIA_REFERENCE_RLS = """
ALTER TABLE media_mediareference ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_mediareference FORCE ROW LEVEL SECURITY;
CREATE POLICY media_reference_tenant_isolation ON media_mediareference
USING (
    organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid
)
WITH CHECK (
    organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid
);
"""

DISABLE_MEDIA_REFERENCE_RLS = """
DROP POLICY IF EXISTS media_reference_tenant_isolation ON media_mediareference;
ALTER TABLE media_mediareference NO FORCE ROW LEVEL SECURITY;
ALTER TABLE media_mediareference DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_add_media_processing_results"),
        ("organizations", "0014_add_media_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("sites.page_version", "Wersja strony"),
                            ("sites.publication", "Publikacja"),
                        ],
                        max_length=80,
                    ),
                ),
                ("owner_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="references",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "owner_type", "owner_id", "asset_id"),
                "indexes": [
                    models.Index(
                        fields=["organization", "owner_type", "owner_id"],
                        name="media_ref_org_owner_idx",
                    ),
                    models.Index(
                        fields=["organization", "asset", "owner_type"],
                        name="media_ref_org_asset_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "owner_type", "owner_id", "asset"),
                        name="media_ref_org_owner_asset_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            "owner_type__in",
                            ["sites.page_version", "sites.publication"],
                        )),
                        name="media_ref_owner_type_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            ENABLE_MEDIA_REFERENCE_RLS,
            reverse_sql=DISABLE_MEDIA_REFERENCE_RLS,
        ),
    ]
