# Generated by Django 5.2.17 on 2026-08-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

CREATE_MEDIA_DELETE_GUARDS = """
CREATE OR REPLACE FUNCTION media_protect_asset_tombstone()
RETURNS trigger AS $$
BEGIN
    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL AND (
        NEW.deleted_by_id IS NULL OR NEW.deletion_idempotency_key = ''
    ) THEN
        RAISE EXCEPTION 'media tombstone requires actor and idempotency key'
            USING ERRCODE = '23514';
    END IF;
    IF OLD.deleted_at IS NOT NULL AND (
        NEW.deleted_at IS DISTINCT FROM OLD.deleted_at
        OR NEW.deleted_by_id IS DISTINCT FROM OLD.deleted_by_id
        OR NEW.deletion_idempotency_key IS DISTINCT FROM OLD.deletion_idempotency_key
    ) THEN
        RAISE EXCEPTION 'media tombstone is immutable' USING ERRCODE = '55000';
    END IF;
    IF NEW.cleanup_completed_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        RAISE EXCEPTION 'media cleanup requires tombstone' USING ERRCODE = '23514';
    END IF;
    IF OLD.cleanup_completed_at IS NOT NULL
       AND NEW.cleanup_completed_at IS DISTINCT FROM OLD.cleanup_completed_at THEN
        RAISE EXCEPTION 'media cleanup completion is immutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER media_asset_tombstone_guard
BEFORE UPDATE ON media_mediaasset
FOR EACH ROW EXECUTE FUNCTION media_protect_asset_tombstone();

CREATE OR REPLACE FUNCTION media_protect_reference()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'media reference is append-only' USING ERRCODE = '55000';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER media_reference_append_only_guard
BEFORE UPDATE OR DELETE ON media_mediareference
FOR EACH ROW EXECUTE FUNCTION media_protect_reference();
"""

DROP_MEDIA_DELETE_GUARDS = """
DROP TRIGGER IF EXISTS media_reference_append_only_guard ON media_mediareference;
DROP FUNCTION IF EXISTS media_protect_reference();
DROP TRIGGER IF EXISTS media_asset_tombstone_guard ON media_mediaasset;
DROP FUNCTION IF EXISTS media_protect_asset_tombstone();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_mediareference"),
        ("organizations", "0014_add_media_role_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="cleanup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deleted_media_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="deletion_idempotency_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization", "deleted_at", "cleanup_completed_at"],
                name="media_asset_cleanup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediaasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_by__isnull", False),
                    models.Q(("deletion_idempotency_key", ""), _negated=True),
                ),
                fields=("organization", "deleted_by", "deletion_idempotency_key"),
                name="media_asset_org_actor_delete_idem_uq",
            ),
        ),
        migrations.RunSQL(
            CREATE_MEDIA_DELETE_GUARDS,
            reverse_sql=DROP_MEDIA_DELETE_GUARDS,
        ),
    ]
