# Generated by Django 5.2.17 on 2026-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_entry_version_media_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediareference',
            name='owner_type',
            field=models.CharField(choices=[('sites.page_version', 'Wersja strony'), ('sites.content_entry_version', 'Wersja wpisu'), ('sites.publication', 'Publikacja')], max_length=80),
        ),
    ]
