# Generated by Django 5.2.17 on 2026-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    """Lets a version of an organization's own template (F4-B) keep the photos
    it was saved with; the check constraint lists the owners the database
    accepts, as in 0005."""

    dependencies = [
        ('media', '0008_mediaasset_ai_origin'),
        ('organizations', '0051_audit_crews_teams'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediareference',
            name='media_ref_owner_type_ck',
        ),
        migrations.AlterField(
            model_name='mediareference',
            name='owner_type',
            field=models.CharField(choices=[('sites.page_version', 'Wersja strony'), ('sites.content_entry_version', 'Wersja wpisu'), ('sites.publication', 'Publikacja'), ('sites.template_version', 'Wersja szablonu')], max_length=80),
        ),
        migrations.AddConstraint(
            model_name='mediareference',
            constraint=models.CheckConstraint(condition=models.Q(('owner_type__in', ['sites.page_version', 'sites.content_entry_version', 'sites.publication', 'sites.template_version'])), name='media_ref_owner_type_ck'),
        ),
    ]
