# Generated by Django 5.2.17 on 2026-09-20 05:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0004_grant_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmActivationCode",
            fields=[
                (
                    "token_digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("company_organization_id", models.UUIDField()),
                ("farm_id", models.UUIDField()),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_by_organization_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["farm_id", "used_at"], name="farms_code_farm_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="FarmShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("registry_organization_id", models.UUIDField()),
                ("registry_farm_id", models.UUIDField()),
                ("company_organization_id", models.UUIDField()),
                ("company_farm_id", models.UUIDField()),
                ("can_write_herd", models.BooleanField(default=True)),
                ("can_publish_health", models.BooleanField(default=True)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("activation_code", "Kod aktywacji od firmy"),
                            ("support", "Połączenie przez obsługę platformy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktywny"), ("revoked", "Cofnięty")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("registry_organization_id", "-granted_at"),
                "indexes": [
                    models.Index(
                        fields=["registry_organization_id"], name="farms_share_registry_idx"
                    ),
                    models.Index(
                        fields=["company_organization_id"], name="farms_share_company_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("registry_farm_id", "company_farm_id"), name="farms_share_pair_uq"
                    )
                ],
            },
        ),
    ]
