# Generated by Django 5.2.17 on 2026-09-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmactivationcode',
            name='company_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='farmactivationcode',
            name='handover',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='farmshare',
            name='company_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='farmshare',
            name='registry_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
