# Generated by Django 5.2.17 on 2026-09-20 10:30

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_handover_payload'),
        ('organizations', '0040_audit_farm_share_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHealthEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('occurred_on', models.DateField()),
                ('source', models.CharField(max_length=32)),
                ('source_reference', models.CharField(max_length=64)),
                ('author_name', models.CharField(blank=True, max_length=160)),
                ('author_organization_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.CharField(max_length=240)),
                ('details', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_entries', to='farms.animal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', '-occurred_on', '-published_at'),
                'indexes': [models.Index(fields=['organization', 'animal'], name='farms_health_animal_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'animal', 'source', 'source_reference'), name='farms_health_source_uq')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
