# Generated by Django 5.2.17 on 2026-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_animal_health_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animalhealthentry',
            name='author_organization_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='animalhealthentry',
            name='kind',
            field=models.CharField(choices=[('note', 'Notatka'), ('alert', 'Uwaga'), ('treatment', 'Zabieg'), ('medication', 'Lek lub szczepienie'), ('visit', 'Wizyta specjalisty')], default='note', max_length=16),
        ),
        migrations.AddField(
            model_name='animalhealthentry',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
