# Generated by Django 5.2.17 on 2026-09-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_health_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealthentry',
            name='photos',
            field=models.JSONField(default=list),
        ),
    ]
