# Generated by Django 5.2.17 on 2026-09-21 05:30

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0010_health_photos"),
        ("organizations", "0042_audit_herd_pushed"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmshare",
            name="can_publish_schedule",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FarmVisitEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("source_reference", models.CharField(max_length=64)),
                ("company_organization_id", models.UUIDField()),
                ("company_name", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Zaplanowana"),
                            ("done", "Odbyta"),
                            ("canceled", "Odwołana"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("details", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_entries",
                        to="farms.farm",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-scheduled_for", "-occurred_on"),
                "indexes": [
                    models.Index(fields=["organization", "farm"], name="farms_visit_farm_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "farm",
                            "company_organization_id",
                            "source",
                            "source_reference",
                        ),
                        name="farms_visit_source_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
