# Generated by Django 5.2.17 on 2026-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farms", "0012_farm_visits_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalhealthentry",
            name="withdrawal_meat_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animalhealthentry",
            name="withdrawal_milk_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
