# Generated by Django 5.2.17 on 2026-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0014_health_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealthentry',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
