# Generated by Django 5.2.17 on 2026-09-06 10:47

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0006_alter_mediareference_owner_type'),
        ('organizations', '0029_alter_organizationauditentry_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('subject_kind', models.CharField(choices=[('organization', 'Organizacja'), ('person', 'Osoba')], max_length=16)),
                ('display_name', models.CharField(max_length=160)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=4000)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_address', models.CharField(blank=True, max_length=240)),
                ('links', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('locale', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], default='pl', max_length=10)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.mediaasset')),
            ],
            options={
                'ordering': ('organization_id', 'subject_kind', 'display_name', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PublicProfileTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], max_length=10)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=4000)),
                ('allow_headline_fallback', models.BooleanField(default=True)),
                ('allow_bio_fallback', models.BooleanField(default=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='profiles.publicprofile')),
            ],
            options={
                'ordering': ('organization_id', 'profile_id', 'locale'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='publicprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_kind', 'organization')), fields=('organization',), name='profiles_single_organization_profile_uq'),
        ),
        migrations.AddConstraint(
            model_name='publicprofile',
            constraint=models.CheckConstraint(condition=models.Q(('subject_kind', 'person'), ('membership__isnull', True), _connector='OR'), name='profiles_membership_only_for_person_ck'),
        ),
        migrations.AddConstraint(
            model_name='publicprofiletranslation',
            constraint=models.UniqueConstraint(fields=('organization', 'profile', 'locale'), name='profiles_translation_org_profile_locale_uq'),
        ),
    ]
