# Generated by Django 5.2.17 on 2026-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0009_template_version_media_owner"),
        ("organizations", "0053_organization_public_locales"),
        ("profiles", "0005_public_locales_from_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicprofile",
            name="locale",
            field=models.CharField(default="pl", max_length=10),
        ),
        migrations.AlterField(
            model_name="publicprofiletranslation",
            name="locale",
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name="publicprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="profiles_profile_locale_format_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicprofiletranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="profiles_translation_locale_format_ck",
            ),
        ),
    ]
