# Generated by Django 5.2.17 on 2026-10-03 02:56

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0057_alter_organizationauditentry_action'),
        ('profiles', '0006_content_locale_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprofiletranslation',
            name='link_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publicprofiletranslation',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProfileTranslationWrite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=10)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('job_ref', models.CharField(blank=True, default='', max_length=160)),
                ('outcomes', models.JSONField(default=list)),
                ('replaced', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.publicprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'job_ref'], name='profiles_pr_organiz_74a8bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'profile', 'locale', 'idempotency_key'), name='profiles_translationwrite_idem_uq')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
