# Generated by Django 5.2.17 on 2026-10-03 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_tenant_isolation_translation_writes'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogentry',
            name='headline_by_locale',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='source_locale',
            field=models.CharField(default='pl', max_length=10),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='translated_locales',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
    ]
