# Generated by Django 5.2.17 on 2026-08-10 20:29

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0006_protect_system_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Klucz musi składać się z co najmniej dwóch segmentów oddzielonych kropką.",
                                regex="^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("module", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="QuotaDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Klucz musi składać się z co najmniej dwóch segmentów oddzielonych kropką.",
                                regex="^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "unit",
                    models.CharField(
                        choices=[("count", "Liczba"), ("bytes", "Bajty")], max_length=16
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("lifetime", "Bez resetu"), ("month", "Miesięcznie")],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "currency",
                    models.CharField(
                        default="PLN",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Waluta musi być kodem ISO 4217."
                            )
                        ],
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("month", "Miesięcznie"), ("year", "Rocznie")],
                        default="month",
                        max_length=16,
                    ),
                ),
                ("unit_amount_minor", models.PositiveBigIntegerField()),
                ("feature_keys", models.JSONField(default=list)),
                ("quotas", models.JSONField(default=dict)),
                ("trial_days", models.PositiveSmallIntegerField(default=3)),
                ("grace_period_days", models.PositiveSmallIntegerField(default=7)),
                ("effective_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "ordering": ("plan__key", "version"),
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_plan",
                to="billing.planversion",
            ),
        ),
        migrations.CreateModel(
            name="EntitlementSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "subscription_state",
                    models.CharField(
                        choices=[
                            ("unconfigured", "Nieskonfigurowana"),
                            ("trialing", "Trial"),
                            ("active", "Aktywna"),
                            ("grace_period", "Okres karencji"),
                            ("read_only", "Tylko do odczytu"),
                            ("suspended", "Zawieszona"),
                            ("canceled", "Anulowana"),
                        ],
                        default="unconfigured",
                        max_length=20,
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("full", "Pełny dostęp"),
                            ("read_only", "Tylko do odczytu"),
                            ("blocked", "Zablokowany"),
                        ],
                        default="blocked",
                        max_length=16,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=dict)),
                ("quotas", models.JSONField(blank=True, default=dict)),
                ("sources", models.JSONField(blank=True, default=dict)),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("computed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="billing.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id",),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EntitlementGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("trial", "Trial"),
                            ("promotion", "Promocja"),
                            ("override", "Nadpisanie administracyjne"),
                            ("partner", "Partnerstwo"),
                            ("addon", "Dodatek"),
                        ],
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(blank=True, null=True)),
                ("limit_value", models.PositiveBigIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entitlement_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="billing.feature",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlement_grants",
                        to="billing.planversion",
                    ),
                ),
                (
                    "quota_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="billing.quotadefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "source", "created_at"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("plan", "version"), name="billing_plan_version_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="entitlementsnapshot",
            index=models.Index(
                fields=["organization", "subscription_state"], name="bill_snapshot_org_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementsnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="billing_snapshot_organization_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="entitlementgrant",
            index=models.Index(fields=["organization", "source"], name="bill_grant_org_source_idx"),
        ),
        migrations.AddIndex(
            model_name="entitlementgrant",
            index=models.Index(
                fields=["organization", "expires_at"], name="bill_grant_org_expiry_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("enabled__isnull", False),
                        ("feature__isnull", False),
                        ("limit_value__isnull", True),
                        ("quota_definition__isnull", True),
                    ),
                    models.Q(
                        ("enabled__isnull", True),
                        ("feature__isnull", True),
                        ("limit_value__isnull", False),
                        ("quota_definition__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="billing_grant_target_value_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_at__isnull", True),
                    ("expires_at__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="billing_grant_valid_window_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "override"), _negated=True),
                    models.Q(
                        ("granted_by__isnull", False), models.Q(("reason", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="billing_override_audit_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "plan"), _negated=True),
                    ("plan_version__isnull", False),
                    _connector="OR",
                ),
                name="billing_plan_grant_version_ck",
            ),
        ),
    ]
