# Generated by Django 5.2.17 on 2026-08-10 20:46

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_protect_plan_versions"),
        ("organizations", "0006_protect_system_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField(blank=True, null=True)),
                ("used", models.PositiveBigIntegerField(default=0)),
                ("reserved", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "quota_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_periods",
                        to="billing.quotadefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "quota_definition_id", "period_start"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="QuotaReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                ("amount", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Zarezerwowana"),
                            ("committed", "Rozliczona"),
                            ("released", "Zwolniona"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="billing.quotausage",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "created_at"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="quotausage",
            constraint=models.UniqueConstraint(
                fields=("organization", "quota_definition", "period_start", "period_end"),
                name="billing_quota_usage_period_uq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="quotausage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_end__isnull", True),
                    ("period_end__gt", models.F("period_start")),
                    _connector="OR",
                ),
                name="billing_quota_usage_window_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="quotareservation",
            index=models.Index(
                fields=["organization", "state", "expires_at"], name="bill_reservation_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotareservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="billing_quota_reservation_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotareservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="billing_quota_reservation_amount_ck"
            ),
        ),
    ]
