# Generated by Django 5.2.17 on 2026-08-10 21:32

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_quotausage_quotareservation_and_more"),
        ("organizations", "0007_billingprofile_org_billing_external_customer_uq"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePriceMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_product_id", models.CharField(max_length=160)),
                ("stripe_price_id", models.CharField(max_length=160, unique=True)),
                ("livemode", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_prices",
                        to="billing.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ("plan_version__plan__key", "plan_version__version", "livemode"),
            },
        ),
        migrations.CreateModel(
            name="BillingSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_subscription_id", models.CharField(max_length=160, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("unconfigured", "Nieskonfigurowana"),
                            ("trialing", "Trial"),
                            ("active", "Aktywna"),
                            ("grace_period", "Okres karencji"),
                            ("read_only", "Tylko do odczytu"),
                            ("suspended", "Zawieszona"),
                            ("canceled", "Anulowana"),
                        ],
                        default="unconfigured",
                        max_length=20,
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Niekompletna"),
                            ("incomplete_expired", "Niekompletna i wygasła"),
                            ("trialing", "Trial"),
                            ("active", "Aktywna"),
                            ("past_due", "Płatność zaległa"),
                            ("canceled", "Anulowana"),
                            ("unpaid", "Nieopłacona"),
                            ("paused", "Wstrzymana"),
                        ],
                        max_length=24,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_created_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_id", models.CharField(blank=True, max_length=160)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "price_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.stripepricemapping",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-created_at"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=160, unique=True)),
                ("event_type", models.CharField(max_length=120)),
                ("api_version", models.CharField(blank=True, max_length=32)),
                ("livemode", models.BooleanField()),
                ("provider_created_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Odebrane"),
                            ("processing", "Przetwarzane"),
                            ("processed", "Przetworzone"),
                            ("failed", "Błąd"),
                            ("ignored", "Pominięte"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("processing_error", models.TextField(blank=True)),
                ("signature_verified_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_webhook_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_events",
                        to="billing.billingsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("received_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="stripepricemapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("plan_version", "livemode"),
                name="billing_active_price_plan_mode_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="billingsubscription",
            index=models.Index(fields=["organization", "state"], name="bill_sub_org_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="billingsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "canceled"), _negated=True),
                fields=("organization",),
                name="billing_subscription_current_org_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_period_end__isnull", True), ("current_period_start__isnull", True)
                    ),
                    models.Q(
                        ("current_period_end__isnull", False),
                        ("current_period_start__isnull", False),
                        ("current_period_end__gt", models.F("current_period_start")),
                    ),
                    _connector="OR",
                ),
                name="billing_subscription_period_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("trial_end__isnull", True), ("trial_start__isnull", True)),
                    models.Q(
                        ("trial_end__isnull", False),
                        ("trial_start__isnull", False),
                        ("trial_end__gt", models.F("trial_start")),
                    ),
                    _connector="OR",
                ),
                name="billing_subscription_trial_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(fields=["status", "received_at"], name="bill_webhook_status_idx"),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(
                fields=["event_type", "provider_created_at"], name="bill_webhook_type_idx"
            ),
        ),
    ]
