# Generated by Django 5.2.17 on 2026-08-10 22:05

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_stripepricemapping_billingsubscription_and_more"),
        ("organizations", "0008_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingCheckout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_checkout_session_id", models.CharField(max_length=160, unique=True)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("checkout_url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Otwarty"),
                            ("complete", "Zakończony"),
                            ("expired", "Wygasły"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("setup_intent_id", models.CharField(blank=True, max_length=160)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "price_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="billing.stripepricemapping",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "idempotency_key"),
                        name="billing_checkout_idempotency_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completed_at__isnull", False), ("status", "complete")),
                            models.Q(
                                models.Q(("status", "complete"), _negated=True),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="billing_checkout_completed_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
