# Generated by Django 5.2.17 on 2026-08-10 22:28

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_billingcheckout"),
        ("organizations", "0009_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTrialActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_type", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("active", "Aktywowana"),
                            ("failed", "Błąd"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_activation",
                        to="billing.billingcheckout",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_activation",
                        to="billing.billingsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization",), name="billing_trial_activation_org_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("activated_at__isnull", False),
                                ("status", "active"),
                                ("subscription__isnull", False),
                            ),
                            models.Q(
                                models.Q(("status", "active"), _negated=True),
                                ("activated_at__isnull", True),
                                ("subscription__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="billing_trial_activation_state_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
