# Generated by Django 5.2.17 on 2026-08-10 23:11

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_billingtrialactivation"),
        ("organizations", "0010_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingsubscription",
            name="grace_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BillingLifecycleAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("trial_ending_notice", "Ostrzeżenie o końcu triala"),
                            ("grace_ending_notice", "Ostrzeżenie o końcu karencji"),
                            ("grace_expired", "Koniec karencji"),
                            ("canceled_period_ended", "Koniec opłaconego okresu"),
                        ],
                        max_length=32,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("processed", "Przetworzona"),
                            ("canceled", "Anulowana"),
                            ("failed", "Błąd"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_actions",
                        to="billing.billingsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("due_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BillingNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("trial_ending", "Koniec triala"),
                            ("grace_ending", "Koniec karencji"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lifecycle_action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notice",
                        to="billing.billinglifecycleaction",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="billing.billingsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="billinglifecycleaction",
            index=models.Index(fields=["status", "due_at"], name="bill_lifecycle_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="billinglifecycleaction",
            constraint=models.UniqueConstraint(
                fields=("subscription", "action_type", "due_at"), name="billing_lifecycle_action_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="billinglifecycleaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("processed_at__isnull", False), ("status__in", ["processed", "canceled"])
                    ),
                    models.Q(("status__in", ["pending", "failed"]), ("processed_at__isnull", True)),
                    _connector="OR",
                ),
                name="billing_lifecycle_processed_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="billingnotice",
            index=models.Index(
                fields=["organization", "notice_type", "created_at"],
                name="bill_notice_org_type_idx",
            ),
        ),
    ]
