# Generated by Django 5.2.17 on 2026-08-11 07:51

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_billingsubscription_grace_period_end_and_more"),
        ("organizations", "0011_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("baseline_version", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("succeeded", "Zsynchronizowana"),
                            ("no_change", "Bez zmian"),
                            ("conflict", "Konflikt wersji"),
                            ("failed", "Błąd"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="billing.billingsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_for", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"], name="bill_reconcile_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "scheduled_for"),
                        name="billing_reconciliation_schedule_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completed_at__isnull", True), ("status", "pending")),
                            models.Q(
                                models.Q(("status", "pending"), _negated=True),
                                ("completed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="billing_reconciliation_completed_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
