# Generated by Django 5.2.17 on 2026-08-11 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billingreconciliation'),
        ('organizations', '0012_alter_organizationauditentry_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlementgrant',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('organization', 'idempotency_key'), name='billing_grant_idempotency_uq'),
        ),
    ]
