# Generated by Django 5.2.17 on 2026-08-11 08:38

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_entitlementgrant_idempotency_key_and_more'),
        ('organizations', '0012_alter_organizationauditentry_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoiceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'Przetwarzany'), ('succeeded', 'Obsłużony'), ('failed', 'Błąd')], default='pending', max_length=16)),
                ('adapter_key', models.CharField(default='internal', max_length=64)),
                ('request', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('payment_confirmed_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('origin_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_documents', to='billing.stripewebhookevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_documents', to='billing.billingsubscription')),
            ],
            options={
                'ordering': ('organization_id', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='bill_invoice_org_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status__in', ['pending', 'processing'])), models.Q(('completed_at__isnull', False), ('last_error', ''), ('status', 'succeeded')), models.Q(('completed_at__isnull', False), ('status', 'failed'), models.Q(('last_error', ''), _negated=True)), _connector='OR'), name='billing_invoice_document_state_ck')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
