# Generated by Django 5.2.17 on 2026-09-03 07:20

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_rls_and_tenant_guards"),
        ("organizations", "0022_credits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Klucz musi składać się z co najmniej dwóch segmentów oddzielonych kropką.",
                                regex="^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("cost", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="CreditPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("credits", models.PositiveBigIntegerField()),
                (
                    "currency",
                    models.CharField(
                        default="PLN",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Waluta musi być kodem ISO 4217."
                            )
                        ],
                    ),
                ),
                ("unit_amount_minor", models.PositiveBigIntegerField()),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("credits", "key"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("credits__gt", 0)),
                        name="billing_credit_pack_credits_ck",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("credits", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("unit_amount_minor", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("succeeded", "Opłacony"),
                            ("failed", "Nieudany"),
                            ("canceled", "Anulowany"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=160)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="billing.creditpack",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-created_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CreditReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                ("operation_key", models.CharField(max_length=100)),
                ("cost", models.PositiveIntegerField()),
                ("allowance_amount", models.PositiveIntegerField(default=0)),
                ("purchased_amount", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Zarezerwowane"),
                            ("committed", "Rozliczone"),
                            ("released", "Zwolnione"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "created_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CreditLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("allowance_granted", "Przyznano pulę planu"),
                            ("allowance_expired", "Wygasła pula planu"),
                            ("purchased", "Zakup kredytów"),
                            ("consumed", "Zużycie"),
                            ("refunded", "Zwrot zużycia"),
                            ("operator_adjustment", "Korekta operatora"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[("allowance", "Pula planu"), ("purchased", "Kredyty kupione")],
                        max_length=16,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("balance_after", models.PositiveBigIntegerField()),
                ("operation_key", models.CharField(blank=True, max_length=100)),
                ("operation_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=120)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="billing.creditpurchase",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="billing.creditreservation",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "occurred_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CreditBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("allowance_remaining", models.PositiveBigIntegerField(default=0)),
                ("allowance_reserved", models.PositiveBigIntegerField(default=0)),
                ("allowance_granted", models.PositiveBigIntegerField(default=0)),
                ("allowance_period_start", models.DateField(blank=True, null=True)),
                ("allowance_period_end", models.DateField(blank=True, null=True)),
                ("purchased_remaining", models.PositiveBigIntegerField(default=0)),
                ("purchased_reserved", models.PositiveBigIntegerField(default=0)),
                ("version", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization",), name="billing_credit_balance_org_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            "allowance_reserved__lte",
                            models.F("allowance_remaining"),
                        )),
                        name="billing_credit_allowance_reserved_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            "purchased_reserved__lte",
                            models.F("purchased_remaining"),
                        )),
                        name="billing_credit_purchased_reserved_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("allowance_period_end__isnull", True),
                            ("allowance_period_start__isnull", False),
                            _connector="OR",
                        ),
                        name="billing_credit_allowance_window_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="billing_credit_purchase_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("credits__gt", 0)), name="billing_credit_purchase_credits_ck"
            ),
        ),
        migrations.AddIndex(
            model_name="creditreservation",
            index=models.Index(
                fields=["organization", "state", "expires_at"], name="bill_credit_res_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditreservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="billing_credit_reservation_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__gt", 0)), name="billing_credit_reservation_cost_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditreservation",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "cost",
                    django.db.models.expressions.CombinedExpression(
                        models.F("allowance_amount"), "+", models.F("purchased_amount")
                    ),
                )),
                name="billing_credit_reservation_split_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="creditledgerentry",
            index=models.Index(
                fields=["organization", "occurred_at"], name="bill_credit_ledger_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="billing_credit_ledger_amount_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("organization", "kind", "bucket", "idempotency_key"),
                name="billing_credit_ledger_key_uq",
            ),
        ),
    ]
