# Generated by Django 5.2.17 on 2026-09-03 13:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0017_plan_credit_allowance"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_product_id", models.CharField(max_length=160)),
                ("stripe_price_id", models.CharField(max_length=160, unique=True)),
                ("livemode", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_prices",
                        to="billing.creditpack",
                    ),
                ),
            ],
            options={
                "ordering": ("pack__credits", "livemode"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("pack", "livemode"),
                        name="billing_active_price_pack_mode_uq",
                    )
                ],
            },
        ),
    ]
