# Generated by Django 5.2.17 on 2026-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0018_credit_pack_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditpurchase",
            name="checkout_session_id",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="creditpurchase",
            name="checkout_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creditpurchase",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
