# Generated by Django 5.2.17 on 2026-09-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_credit_purchase_checkout'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingtrialactivation',
            name='billing_trial_activation_org_uq',
        ),
    ]
