# Generated by Django 5.2.17 on 2026-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0026_assistant_features"),
        ("organizations", "0054_command_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditledgerentry",
            name="operation_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditoperation",
            name="unit",
            field=models.CharField(default="operation", max_length=40),
        ),
        migrations.AddField(
            model_name="creditreservation",
            name="allowance_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditreservation",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="creditreservation",
            name="settled_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditreservation",
            name="unit_cost",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="creditreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="billing_credit_reservation_quantity_ck",
            ),
        ),
    ]
