# Generated by Django 5.2.17 on 2026-10-02 21:02

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0054_command_receipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationGlossaryTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("term", models.CharField(max_length=120)),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("keep", "Keep"),
                            ("name", "Name"),
                            ("translate_as", "Translate as"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_locale", models.CharField(max_length=10)),
                ("target_locale", models.CharField(blank=True, max_length=10)),
                ("translation", models.CharField(blank=True, max_length=120)),
                ("forms", models.JSONField(blank=True, default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "source_locale"],
                        name="translation_organiz_f803d6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        django.db.models.functions.text.Lower("term"),
                        models.F("source_locale"),
                        models.F("target_locale"),
                        name="translation_glossary_term_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rule__in", ["keep", "name", "translate_as"])),
                        name="translation_glossary_term_rule_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("rule", "translate_as"), _negated=True),
                            models.Q(("translation", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="translation_glossary_term_translation_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("term", ""), _negated=True),
                        name="translation_glossary_term_not_empty_ck",
                    ),
                ],
            },
        ),
    ]
