# Generated by Django 5.2.17 on 2026-10-02 21:36

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0054_command_receipt"),
        ("translation", "0004_grant_role_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationCeiling",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(max_length=8)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["none", "review", "off"])),
                        name="translation_ceiling_state_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="translation_ceiling_reason_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranslationMutation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("principal_ref", models.CharField(max_length=80)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("request_hash", models.CharField(max_length=64)),
                ("result_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "action", "principal_ref", "idempotency_key"),
                        name="translation_mutation_idem_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TranslationOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("mode_cap", models.CharField(blank=True, max_length=8)),
                ("auto_monthly_limit_cap", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("mode_cap__in", ["", "review", "off"])),
                        name="translation_override_mode_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="translation_override_reason_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TranslationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("automatic", "Automatic"), ("review", "Review")],
                        max_length=16,
                    ),
                ),
                ("auto_changes", models.BooleanField(blank=True, null=True)),
                ("auto_consent_membership_id", models.UUIDField(blank=True, null=True)),
                ("auto_consent_at", models.DateTimeField(blank=True, null=True)),
                ("auto_monthly_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("processing_ack_membership_id", models.UUIDField(blank=True, null=True)),
                ("processing_ack_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization",), name="translation_settings_org_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mode__in", ["", "automatic", "review"])),
                        name="translation_settings_mode_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("auto_monthly_limit__isnull", True),
                            ("auto_monthly_limit__lte", 100000),
                            _connector="OR",
                        ),
                        name="translation_settings_limit_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="translationglossaryterm",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
