# Generated by Django 5.2.17 on 2026-10-02 21:55

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0055_public_locales_change"),
        ("translation", "0006_tenant_isolation_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("membership_id", models.UUIDField()),
                ("trigger", models.CharField(max_length=16)),
                ("cause", models.CharField(max_length=80)),
                ("billing", models.CharField(max_length=16)),
                ("protected", models.CharField(max_length=16)),
                ("include_unverified", models.BooleanField(default=False)),
                ("quote_digest", models.CharField(max_length=64)),
                ("operation_key", models.CharField(max_length=100)),
                ("unit_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("units", models.PositiveIntegerField(default=0)),
                ("credits", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("next_attempt_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TranslationJobPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("units", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("settled", "Settled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("reservation_key", models.CharField(blank=True, max_length=120)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_characters", models.PositiveIntegerField(default=0)),
                ("settled_units", models.PositiveIntegerField(default=0)),
                ("settled_credits", models.PositiveIntegerField(default=0)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="translation.translationjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TranslationJobItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("source_key", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("locale", models.CharField(max_length=10)),
                ("basis", models.CharField(max_length=16)),
                ("scope", models.CharField(max_length=200)),
                ("quoted_characters", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("written", "Written"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("delivered", models.JSONField(blank=True, default=dict)),
                ("delivered_characters", models.PositiveIntegerField(default=0)),
                ("outcomes", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="translation.translationjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="translation.translationjobpart",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="translationjob",
            index=models.Index(
                fields=["organization", "state", "next_attempt_at"],
                name="translation_organiz_aec6d1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("trigger__in", ["click", "automatic"])),
                name="translation_job_trigger_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("billing__in", ["credits", "platform_budget"])),
                name="translation_job_billing_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationjobpart",
            constraint=models.UniqueConstraint(
                fields=("job", "index"), name="translation_part_index_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="translationjobitem",
            index=models.Index(
                fields=["job", "state", "position"], name="translation_job_id_b5a2ce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="translationjobitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running"])),
                fields=("organization", "source_key", "object_id", "locale"),
                name="translation_item_active_uq",
            ),
        ),
    ]
