# Generated by Django 5.2.17 on 2026-10-02 22:40

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0055_public_locales_change"),
        ("translation", "0008_tenant_isolation_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="reverted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TranslationReviewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_key", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("locale", models.CharField(max_length=10)),
                ("basis", models.CharField(max_length=16)),
                ("basis_version", models.CharField(max_length=200)),
                ("target_version", models.CharField(blank=True, max_length=200)),
                ("reason", models.CharField(max_length=40)),
                ("keys", models.PositiveIntegerField(default=0)),
                ("texts", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("discarded", "Discarded"),
                            ("superseded", "Superseded"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("decided_by_membership_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="translation.translationjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "state", "created_at"],
                        name="translation_organiz_0e8750_idx",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
