# Generated by Django 5.2.17 on 2026-10-02 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0010_tenant_isolation_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="confirmation_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translationjob",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translationjob",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="translationjob",
            name="estimated_usd_micros",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
