# Generated by Django 5.2.17 on 2026-10-03 00:59

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0056_organization_settings"),
        ("translation", "0011_platform_confirmation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationDemand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_key", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("cause", models.CharField(max_length=80)),
                ("first_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("blocked", "Blocked")],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=40)),
                ("check_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "due_at"], name="translation_state_4f7fdf_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_key", "object_id"),
                        name="translation_demand_object_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["waiting", "blocked"])),
                        name="translation_demand_state_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
