# Generated by Django 5.2.17 on 2026-10-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0013_tenant_isolation_demand"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationsettings",
            name="auto_carry_characters",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
