# Generated by Django 5.2.17 on 2026-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tenant_relation_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='appointment_kind',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
