# Generated by Django 5.2.17 on 2026-09-19 13:41

import django.db.models.deletion
from django.db import migrations, models


def _function(relations: str, extra_case: str) -> str:
    return f"""
CREATE OR REPLACE FUNCTION booking_validate_tenant_relations()
RETURNS trigger AS $$
DECLARE
    payload jsonb := to_jsonb(NEW);
    relation_name text;
    relation_id uuid;
    relation_table text;
    relation_ok boolean;
BEGIN
    FOREACH relation_name IN ARRAY ARRAY[{relations}] LOOP
        IF payload ? (relation_name || '_id')
           AND payload->>(relation_name || '_id') IS NOT NULL THEN
            relation_id := (payload->>(relation_name || '_id'))::uuid;
            relation_table := CASE relation_name
                WHEN 'appointment' THEN 'booking_appointment'
                WHEN 'customer' THEN 'booking_customer'
                WHEN 'service' THEN 'booking_service'
                WHEN 'staff' THEN 'booking_staffmember'
                WHEN 'location' THEN 'booking_location'
                WHEN 'resource' THEN 'booking_resource'{extra_case}
            END;
            EXECUTE format(
                'SELECT EXISTS (SELECT 1 FROM %I WHERE id = $1 AND organization_id = $2)',
                relation_table
            ) INTO relation_ok USING relation_id, NEW.organization_id;
            IF NOT relation_ok THEN
                RAISE EXCEPTION 'booking relation belongs to another organization'
                    USING ERRCODE = '23514';
            END IF;
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


BASE = "'appointment', 'customer', 'service', 'staff', 'location', 'resource'"
#: 0003's guard, now also checking that a staff member's account belongs to the
#: organization whose calendar it is in, and mounted on the staff table itself.
WITH_MEMBERSHIP = _function(
    BASE + ", 'membership'", "\n                WHEN 'membership' THEN 'organizations_membership'"
)
PREVIOUS = _function(BASE, "")
STAFF_GUARD = (
    "CREATE TRIGGER booking_staffmember_tenant_guard BEFORE INSERT OR UPDATE "
    "ON booking_staffmember FOR EACH ROW EXECUTE FUNCTION booking_validate_tenant_relations();"
)
DROP_STAFF_GUARD = "DROP TRIGGER IF EXISTS booking_staffmember_tenant_guard ON booking_staffmember;"


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_service_appointment_kind"),
        ("organizations", "0039_audit_farm_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="organizations.membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("membership__isnull", False)),
                fields=("organization", "membership"),
                name="booking_staff_org_membership_uq",
            ),
        ),
        migrations.RunSQL(WITH_MEMBERSHIP + STAFF_GUARD, reverse_sql=DROP_STAFF_GUARD + PREVIOUS),
    ]
