# Generated by Django 5.2.17 on 2026-09-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_staff_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="materials",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="service",
            name="materials",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
