# Generated by Django 5.2.17 on 2026-09-28 11:33

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_grant_schedule_own"),
        ("organizations", "0050_crews_teams"),
        ("profiles", "0004_publish_profiles_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("organization_id", "name", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StaffTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="auto_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="crew_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="customer_notes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="appointment",
            name="needs_assignment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="queue_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Rezerwacja ze strony"),
                    ("moved", "Klient przełożył wizytę"),
                    ("time_off", "Nieobecność"),
                    ("ended", "Odejście z firmy"),
                    ("short", "Za mało osób"),
                    ("joined", "Osoba dołączyła do innej wizyty"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="requested_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="booking.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staff_required",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="service",
            name="public_staff_choice",
            field=models.CharField(
                choices=[("none", "Nikogo"), ("team", "Zespół"), ("person", "Osobę")],
                default="none",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="staff_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="profiles.publicprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("staff_count__gte", 1), ("staff_count__lte", 10)),
                name="booking_service_staff_count_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("public_staff_choice", "person"), _negated=True),
                    ("staff_count", 1),
                    _connector="OR",
                ),
                name="booking_service_person_choice_ck",
            ),
        ),
        migrations.AddField(
            model_name="staffteam",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="requested_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="booking.staffteam",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                condition=models.Q(
                    ("needs_assignment", True), ("auto_assigned", True), _connector="OR"
                ),
                fields=["organization", "starts_at"],
                name="booking_appt_queue_idx",
            ),
        ),
        migrations.AddField(
            model_name="staffteammember",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="staffteammember",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_links",
                to="booking.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="staffteammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="booking.staffteam",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffteam",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("name"),
                name="booking_team_org_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffteammember",
            constraint=models.UniqueConstraint(
                fields=("team", "staff"), name="booking_team_member_uq"
            ),
        ),
    ]
