# Generated by Django 5.2.17 on 2026-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0013_public_locales_from_customers"),
        ("organizations", "0053_organization_public_locales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="locale",
            field=models.CharField(default="pl", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="booking_customer_locale_format_ck",
            ),
        ),
    ]
