# Generated by Django 5.2.17 on 2026-10-02 20:30

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

TABLE = "booking_bookingsetupmutation"
#: The receipts are the organization's like every other booking row (ADR-072 §11).
ENABLE_RLS = f"""
ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY;
CREATE POLICY {TABLE}_tenant_isolation ON {TABLE}
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
"""
DISABLE_RLS = f"""
DROP POLICY IF EXISTS {TABLE}_tenant_isolation ON {TABLE};
ALTER TABLE {TABLE} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_content_locale_strings'),
        ('organizations', '0054_command_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resource',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='hours_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BookingSetupMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('principal_ref', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('result_kind', models.CharField(max_length=24)),
                ('result_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'action', 'principal_ref', 'idempotency_key'), name='booking_setup_mutation_idem_uq')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(ENABLE_RLS, reverse_sql=DISABLE_RLS),
    ]
