# Generated by Django 5.2.17 on 2026-10-02 21:01

import uuid
from typing import Any

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models


def _function(relations: str, extra_case: str) -> str:
    return f"""
CREATE OR REPLACE FUNCTION booking_validate_tenant_relations()
RETURNS trigger AS $$
DECLARE
    payload jsonb := to_jsonb(NEW);
    relation_name text;
    relation_id uuid;
    relation_table text;
    relation_ok boolean;
BEGIN
    FOREACH relation_name IN ARRAY ARRAY[{relations}] LOOP
        IF payload ? (relation_name || '_id')
           AND payload->>(relation_name || '_id') IS NOT NULL THEN
            relation_id := (payload->>(relation_name || '_id'))::uuid;
            relation_table := CASE relation_name
                WHEN 'appointment' THEN 'booking_appointment'
                WHEN 'customer' THEN 'booking_customer'
                WHEN 'service' THEN 'booking_service'
                WHEN 'staff' THEN 'booking_staffmember'
                WHEN 'location' THEN 'booking_location'
                WHEN 'resource' THEN 'booking_resource'{extra_case}
            END;
            EXECUTE format(
                'SELECT EXISTS (SELECT 1 FROM %I WHERE id = $1 AND organization_id = $2)',
                relation_table
            ) INTO relation_ok USING relation_id, NEW.organization_id;
            IF NOT relation_ok THEN
                RAISE EXCEPTION 'booking relation belongs to another organization'
                    USING ERRCODE = '23514';
            END IF;
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


CREWS = (
    "'appointment', 'customer', 'service', 'staff', 'location', 'resource', 'membership', "
    "'invitation', 'team', 'requested_team', 'requested_staff', 'profile'"
)
CREWS_CASE = (
    "\n                WHEN 'membership' THEN 'organizations_membership'"
    "\n                WHEN 'invitation' THEN 'organizations_invitation'"
    "\n                WHEN 'team' THEN 'booking_staffteam'"
    "\n                WHEN 'requested_team' THEN 'booking_staffteam'"
    "\n                WHEN 'requested_staff' THEN 'booking_staffmember'"
    "\n                WHEN 'profile' THEN 'profiles_publicprofile'"
)
#: 0010's guard, now also checking a unit's group and a block's allocation.
WITH_UNITS = _function(
    CREWS + ", 'group', 'time_off'",
    CREWS_CASE
    + "\n                WHEN 'group' THEN 'booking_resourcegroup'"
    + "\n                WHEN 'time_off' THEN 'booking_timeoff'",
)
PREVIOUS = _function(CREWS, CREWS_CASE)

#: A unit names its group and its place: both the organization's own.
RESOURCE_GUARD = (
    "CREATE TRIGGER booking_resource_tenant_guard BEFORE INSERT OR UPDATE "
    "ON booking_resource FOR EACH ROW EXECUTE FUNCTION booking_validate_tenant_relations();"
)
DROP_RESOURCE_GUARD = "DROP TRIGGER IF EXISTS booking_resource_tenant_guard ON booking_resource;"

GROUP_TABLE = "booking_resourcegroup"
GROUP_RLS = f"""
ALTER TABLE {GROUP_TABLE} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {GROUP_TABLE} FORCE ROW LEVEL SECURITY;
CREATE POLICY {GROUP_TABLE}_tenant_isolation ON {GROUP_TABLE}
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
"""
NO_GROUP_RLS = f"""
DROP POLICY IF EXISTS {GROUP_TABLE}_tenant_isolation ON {GROUP_TABLE};
ALTER TABLE {GROUP_TABLE} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {GROUP_TABLE} DISABLE ROW LEVEL SECURITY;
"""


def hold_blocks(apps: Any, schema_editor: Any) -> None:
    """Every existing block of a resource gets the allocation that holds its
    time (ADR-072, Konsekwencje). Nobody checked blocks against bookings
    before, so one that already overlaps a booking or an earlier block of the
    same resource gets an inactive one — otherwise the exclusion constraint
    would stop the migration — and is counted in the report. It keeps the
    resource busy in search all the same. Runs as the table owner, so FORCE
    RLS does not hide other tenants' rows."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, organization_id, resource_id, starts_at, ends_at FROM booking_timeoff "
            "WHERE resource_id IS NOT NULL ORDER BY created_at, id"
        )
        blocks = cursor.fetchall()
        overlapping = 0
        for block_id, organization_id, resource_id, starts_at, ends_at in blocks:
            cursor.execute(
                "SELECT EXISTS (SELECT 1 FROM booking_appointmentresourceallocation "
                "WHERE organization_id = %s AND resource_id = %s AND active "
                "AND occupied_range && tstzrange(%s, %s))",
                [organization_id, resource_id, starts_at, ends_at],
            )
            busy = cursor.fetchone()[0]
            cursor.execute(
                "INSERT INTO booking_appointmentresourceallocation "
                "(id, organization_id, time_off_id, resource_id, occupied_range, active) "
                "VALUES (%s, %s, %s, %s, tstzrange(%s, %s), %s)",
                [
                    uuid.uuid7(),
                    organization_id,
                    block_id,
                    resource_id,
                    starts_at,
                    ends_at,
                    not busy,
                ],
            )
            overlapping += int(busy)
    if blocks:
        print(
            f"\n  booking: {len(blocks)} blokad zasobów z alokacją, w tym {overlapping} "
            "nieaktywnych (nachodziły na rezerwację albo wcześniejszą blokadę)"
        )


def release_blocks(apps: Any, schema_editor: Any) -> None:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "DELETE FROM booking_appointmentresourceallocation WHERE time_off_id IS NOT NULL"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0015_setup_receipts_and_versions"),
        ("organizations", "0054_command_receipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("organization_id", "name", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="appointmentresourceallocation",
            name="time_off",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_allocations",
                to="booking.timeoff",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="resource",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="booking.location",
            ),
        ),
        migrations.AddField(
            model_name="timeoff",
            name="external_uid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="timeoff",
            name="source",
            field=models.CharField(
                choices=[("manual", "Ręczna"), ("ical", "Kalendarz zewnętrzny")],
                default="manual",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentresourceallocation",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_allocations",
                to="booking.appointment",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentresourceallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("appointment__isnull", False), ("time_off__isnull", True)),
                    models.Q(("appointment__isnull", True), ("time_off__isnull", False)),
                    _connector="OR",
                ),
                name="booking_resource_allocation_owner_ck",
            ),
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="booking.resourcegroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity__isnull", True), ("capacity__gte", 1), _connector="OR"
                ),
                name="booking_resource_capacity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcegroup",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("name"),
                name="booking_resourcegroup_org_name_uq",
            ),
        ),
        migrations.RunSQL(GROUP_RLS, reverse_sql=NO_GROUP_RLS),
        migrations.RunSQL(WITH_UNITS, reverse_sql=PREVIOUS),
        migrations.RunSQL(RESOURCE_GUARD, reverse_sql=DROP_RESOURCE_GUARD),
        migrations.RunPython(hold_blocks, release_blocks),
    ]
