# Generated by Django 5.2.17 on 2026-10-02 21:22

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models

TABLES = ("booking_bookingrule", "booking_bookingclosure")


def _enable() -> str:
    statements: list[str] = []
    for table in TABLES:
        statements += [
            f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;",
            f"CREATE POLICY {table}_tenant_isolation ON {table} "
            "USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid) "
            "WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);",
            # A season names an offer, a group or a unit, a closure a place:
            # each the organization's own (0016's guard knows all four).
            f"CREATE TRIGGER {table}_tenant_guard BEFORE INSERT OR UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION booking_validate_tenant_relations();",
        ]
    return "\n".join(statements)


def _disable() -> str:
    statements: list[str] = []
    for table in reversed(TABLES):
        statements += [
            f"DROP TRIGGER IF EXISTS {table}_tenant_guard ON {table};",
            f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table};",
            f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;",
            f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;",
        ]
    return "\n".join(statements)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_units_groups_and_blocks'),
        ('organizations', '0054_command_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='booking.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'starts_on', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='booking_closure_dates_ck')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('min_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_multiple', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('end_weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('notice_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('window_days', models.PositiveIntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('buffer_after_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_rules', to='booking.resourcegroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_rules', to='booking.resource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_rules', to='booking.service')),
            ],
            options={
                'ordering': ('organization_id', 'starts_on', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('resource__isnull', True), ('service__isnull', False)), models.Q(('group__isnull', False), ('resource__isnull', True), ('service__isnull', True)), models.Q(('group__isnull', True), ('resource__isnull', False), ('service__isnull', True)), _connector='OR'), name='booking_rule_one_scope_ck'), models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='booking_rule_dates_ck'), models.CheckConstraint(condition=models.Q(('min_length__isnull', True), ('max_length__isnull', True), ('max_length__gte', models.F('min_length')), _connector='OR'), name='booking_rule_length_ck'), models.CheckConstraint(condition=models.Q(('start_weekdays__contained_by', [0, 1, 2, 3, 4, 5, 6]), ('end_weekdays__contained_by', [0, 1, 2, 3, 4, 5, 6])), name='booking_rule_weekdays_ck')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(_enable(), reverse_sql=_disable()),
    ]
