# Generated by Django 5.2.17 on 2026-10-02 21:42

import importlib
import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

_UNITS = importlib.import_module(
    "saas_core.modules.shared.booking.migrations.0016_units_groups_and_blocks"
)
#: 0016's guard, now also checking the group a stay was booked in.
WITH_STAYS = _UNITS._function(
    _UNITS.CREWS + ", 'group', 'time_off', 'requested_group'",
    _UNITS.CREWS_CASE
    + "\n                WHEN 'group' THEN 'booking_resourcegroup'"
    + "\n                WHEN 'time_off' THEN 'booking_timeoff'"
    + "\n                WHEN 'requested_group' THEN 'booking_resourcegroup'",
)

TABLE = "booking_servicegroup"
#: An offer's groups are the organization's own like its other links; 0016's
#: guard knows both a service and a group.
ENABLE = f"""
ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY;
CREATE POLICY {TABLE}_tenant_isolation ON {TABLE}
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
CREATE TRIGGER {TABLE}_tenant_guard BEFORE INSERT OR UPDATE ON {TABLE}
FOR EACH ROW EXECUTE FUNCTION booking_validate_tenant_relations();
"""
DISABLE = f"""
DROP TRIGGER IF EXISTS {TABLE}_tenant_guard ON {TABLE};
DROP POLICY IF EXISTS {TABLE}_tenant_isolation ON {TABLE};
ALTER TABLE {TABLE} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_seasons_and_closures'),
        ('organizations', '0054_command_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='booking_service_duration_ck',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='booking_service_staff_count_ck',
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='booking.resourcegroup'),
        ),
        migrations.AddField(
            model_name='service',
            name='range_end_local',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='range_start_local',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='range_unit',
            field=models.CharField(blank=True, choices=[('night', 'Noc'), ('day', 'Dzień'), ('hour', 'Godzina')], max_length=8),
        ),
        migrations.AddField(
            model_name='service',
            name='time_model',
            field=models.CharField(choices=[('slot', 'Termin'), ('range', 'Okres'), ('session', 'Wydarzenie')], default='slot', max_length=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.staffmember'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('staff_required', 0)), models.Q(('staff__isnull', False), ('staff_required__gte', 1)), _connector='OR'), name='booking_appointment_staff_ck'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_minutes__isnull', True), ('time_model', 'range')), models.Q(models.Q(('time_model', 'range'), _negated=True), ('duration_minutes__gte', 5), ('duration_minutes__lte', 1440)), _connector='OR'), name='booking_service_duration_ck'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('range_unit__in', ['night', 'day', 'hour']), ('time_model', 'range')), models.Q(models.Q(('time_model', 'range'), _negated=True), ('range_unit', '')), _connector='OR'), name='booking_service_range_unit_ck'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff_count__gte', 1), ('staff_count__lte', 10)), models.Q(models.Q(('time_model', 'slot'), _negated=True), ('staff_count', 0)), _connector='OR'), name='booking_service_staff_count_ck'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_links', to='booking.resourcegroup'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_links', to='booking.service'),
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.UniqueConstraint(fields=('service', 'group'), name='booking_service_group_uq'),
        ),
        migrations.RunSQL(ENABLE, reverse_sql=DISABLE),
        migrations.RunSQL(WITH_STAYS, reverse_sql=_UNITS.WITH_UNITS),
    ]
