# Generated by Django 5.2.17 on 2026-10-03 04:10

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0020_tenant_isolation_item_translations"),
        ("organizations", "0057_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="customer_service_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name="CatalogTranslationWrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("job_ref", models.CharField(blank=True, default="", max_length=160)),
                ("outcomes", models.JSONField(default=list)),
                ("replaced", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "job_ref"], name="booking_cat_organiz_8b9650_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "locale", "idempotency_key"),
                        name="booking_catalogtranslationwrite_idem_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
