# Generated by Django 5.2.17 on 2026-10-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_tenant_isolation_catalog_writes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='self_service_cutoff_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='self_service_mode',
            field=models.CharField(default='change_and_cancel', max_length=24),
        ),
        migrations.AddField(
            model_name='location',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slot_step_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
