# Generated by Django 5.2.17 on 2026-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_self_service_terms_online_slot_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='origin_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='service',
            name='preset_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='preset_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='vocabulary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
