# Generated by Django 5.2.17 on 2026-10-03 13:10

import importlib
import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models

_UNITS = importlib.import_module(
    "saas_core.modules.shared.booking.migrations.0016_units_groups_and_blocks"
)
_STAYS = importlib.import_module(
    "saas_core.modules.shared.booking.migrations.0018_stays_and_staffless_offers"
)
#: 0018's guard, now also checking the category a translation names.
WITH_CATEGORIES = _UNITS._function(
    _UNITS.CREWS + ", 'group', 'time_off', 'requested_group', 'category'",
    _UNITS.CREWS_CASE
    + "\n                WHEN 'group' THEN 'booking_resourcegroup'"
    + "\n                WHEN 'time_off' THEN 'booking_timeoff'"
    + "\n                WHEN 'requested_group' THEN 'booking_resourcegroup'"
    + "\n                WHEN 'category' THEN 'booking_participantcategory'",
)

#: A price names an offer, a group or a unit, a category's translation its
#: category: each the organization's own. A category names nothing.
TABLES = (
    ("booking_participantcategory", False),
    ("booking_pricerule", True),
    ("booking_participantcategorytranslation", True),
)
TENANT = "NULLIF(current_setting('app.organization_id', true), '')::uuid"
ENABLE = "\n".join(
    f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {table}_tenant_isolation ON {table}
USING (organization_id = {TENANT})
WITH CHECK (organization_id = {TENANT});
"""
    + (
        f"""CREATE TRIGGER {table}_tenant_guard BEFORE INSERT OR UPDATE ON {table}
FOR EACH ROW EXECUTE FUNCTION booking_validate_tenant_relations();
"""
        if guarded
        else ""
    )
    for table, guarded in TABLES
)
DISABLE = "\n".join(
    f"""
DROP TRIGGER IF EXISTS {table}_tenant_guard ON {table};
DROP POLICY IF EXISTS {table}_tenant_isolation ON {table};
ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
"""
    for table, _guarded in reversed(TABLES)
)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_service_origin_and_draft'),
        ('organizations', '0059_inventory_audit_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('counts_towards_capacity', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'name', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantCategoryTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=10)),
                ('texts', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='booking.participantcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('local_from', models.TimeField(blank=True, null=True)),
                ('local_to', models.TimeField(blank=True, null=True)),
                ('basis', models.CharField(choices=[('per_booking', 'Za rezerwację'), ('per_time_unit', 'Za jednostkę czasu'), ('per_person', 'Za osobę'), ('per_group', 'Za grupę')], max_length=16)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('vat_code', models.CharField(choices=[('23', '23%'), ('8', '8%'), ('5', '5%'), ('0', '0%'), ('zw', 'zw.'), ('np', 'np.')], default='23', max_length=2)),
                ('included_people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra_person_amount_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_person_per_time_unit', models.BooleanField(default=False)),
                ('category_prices', models.JSONField(blank=True, default=list)),
                ('length_discounts', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='booking.resourcegroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='booking.resource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_rules', to='booking.service')),
            ],
            options={
                'ordering': ('organization_id', 'starts_on', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='participantcategory',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('name'), name='booking_participantcategory_org_name_uq'),
        ),
        migrations.AddConstraint(
            model_name='participantcategorytranslation',
            constraint=models.UniqueConstraint(fields=('organization', 'category', 'locale'), name='booking_category_tr_uq'),
        ),
        migrations.AddConstraint(
            model_name='participantcategorytranslation',
            constraint=models.CheckConstraint(condition=models.Q(('locale__regex', '^[a-z]{2}$')), name='booking_category_tr_locale_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('resource__isnull', True), ('service__isnull', False)), models.Q(('group__isnull', False), ('resource__isnull', True), ('service__isnull', True)), models.Q(('group__isnull', True), ('resource__isnull', False), ('service__isnull', True)), _connector='OR'), name='booking_price_one_scope_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_on__isnull', True), ('starts_on__isnull', True)), models.Q(('ends_on__gte', models.F('starts_on')), ('ends_on__isnull', False), ('starts_on__isnull', False)), _connector='OR'), name='booking_price_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('local_from__isnull', True), ('local_to__isnull', True)), models.Q(('local_from__isnull', False), ('local_to__gt', models.F('local_from')), ('local_to__isnull', False)), _connector='OR'), name='booking_price_hours_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(('weekdays__contained_by', [0, 1, 2, 3, 4, 5, 6])), name='booking_price_weekdays_ck'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='booking_price_currency_ck'),
        ),
        migrations.RunSQL(WITH_CATEGORIES, reverse_sql=_STAYS.WITH_STAYS),
        migrations.RunSQL(ENABLE, reverse_sql=DISABLE),
    ]
