# Generated by Django 5.2.17 on 2026-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='quote',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='quote_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
