# Generated by Django 5.2.17 on 2026-10-03 13:46

import importlib
import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

_UNITS = importlib.import_module(
    "saas_core.modules.shared.booking.migrations.0016_units_groups_and_blocks"
)
_PRICES = importlib.import_module("saas_core.modules.shared.booking.migrations.0025_price_list")
#: 0025's guard, now also checking the extra a translation names.
WITH_EXTRAS = _UNITS._function(
    _UNITS.CREWS + ", 'group', 'time_off', 'requested_group', 'category', 'extra'",
    _UNITS.CREWS_CASE
    + "\n                WHEN 'group' THEN 'booking_resourcegroup'"
    + "\n                WHEN 'time_off' THEN 'booking_timeoff'"
    + "\n                WHEN 'requested_group' THEN 'booking_resourcegroup'"
    + "\n                WHEN 'category' THEN 'booking_participantcategory'"
    + "\n                WHEN 'extra' THEN 'booking_extra'",
)

#: An extra names its offer, its translation the extra: each the organization's own.
TABLES = ("booking_extra", "booking_extratranslation")
TENANT = "NULLIF(current_setting('app.organization_id', true), '')::uuid"
ENABLE = "\n".join(
    f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {table}_tenant_isolation ON {table}
USING (organization_id = {TENANT})
WITH CHECK (organization_id = {TENANT});
CREATE TRIGGER {table}_tenant_guard BEFORE INSERT OR UPDATE ON {table}
FOR EACH ROW EXECUTE FUNCTION booking_validate_tenant_relations();
"""
    for table in TABLES
)
DISABLE = "\n".join(
    f"""
DROP TRIGGER IF EXISTS {table}_tenant_guard ON {table};
DROP POLICY IF EXISTS {table}_tenant_isolation ON {table};
ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
"""
    for table in reversed(TABLES)
)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_appointment_quote'),
        ('organizations', '0059_inventory_audit_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('charge', 'Dopłata'), ('security_deposit', 'Kaucja')], default='charge', max_length=16)),
                ('basis', models.CharField(choices=[('per_booking', 'Za rezerwację'), ('per_time_unit', 'Za jednostkę czasu'), ('per_person', 'Za osobę'), ('per_person_per_time_unit', 'Za osobę i jednostkę czasu')], default='per_booking', max_length=24)),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('vat_code', models.CharField(choices=[('23', '23%'), ('8', '8%'), ('5', '5%'), ('0', '0%'), ('zw', 'zw.'), ('np', 'np.')], default='23', max_length=2)),
                ('mandatory', models.BooleanField(default=False)),
                ('max_quantity', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='booking.service')),
            ],
            options={
                'ordering': ('organization_id', 'name', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=10)),
                ('texts', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='booking.extra')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='extra',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__gte', 1)), name='booking_extra_quantity_ck'),
        ),
        migrations.AddConstraint(
            model_name='extra',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='booking_extra_currency_ck'),
        ),
        migrations.AddConstraint(
            model_name='extra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'security_deposit'), _negated=True), models.Q(('basis', 'per_booking'), ('mandatory', True), ('max_quantity', 1), ('vat_code', 'np')), _connector='OR'), name='booking_extra_deposit_ck'),
        ),
        migrations.AddConstraint(
            model_name='extratranslation',
            constraint=models.UniqueConstraint(fields=('organization', 'extra', 'locale'), name='booking_extra_tr_uq'),
        ),
        migrations.AddConstraint(
            model_name='extratranslation',
            constraint=models.CheckConstraint(condition=models.Q(('locale__regex', '^[a-z]{2}$')), name='booking_extra_tr_locale_ck'),
        ),
        migrations.RunSQL(WITH_EXTRAS, reverse_sql=_PRICES.WITH_CATEGORIES),
        migrations.RunSQL(ENABLE, reverse_sql=DISABLE),
    ]
