# Generated by Django 5.2.17 on 2026-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment_policy',
            field=models.CharField(choices=[('none', 'Nie określono'), ('on_site', 'Płatność na miejscu')], default='none', max_length=16),
        ),
    ]
