# Generated by Django 5.2.17 on 2026-10-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0029_customer_to_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="hold_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="deposit_percent",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="service",
            name="transfer_due_days",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Czeka na wpłatę"),
                    ("confirmed", "Potwierdzona"),
                    ("completed", "Zakończona"),
                    ("canceled", "Anulowana"),
                    ("no_show", "Nieobecność"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Czeka na wpłatę"),
                    ("confirmed", "Potwierdzona"),
                    ("completed", "Zakończona"),
                    ("canceled", "Anulowana"),
                    ("no_show", "Nieobecność"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="payment_policy",
            field=models.CharField(
                choices=[
                    ("none", "Nie określono"),
                    ("on_site", "Płatność na miejscu"),
                    ("transfer", "Przelew przed wizytą"),
                    ("deposit", "Przedpłata"),
                    ("full", "Całość z góry"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
