# Generated by Django 5.2.17 on 2026-10-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0030_prepayment_and_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="confirmation",
            field=models.CharField(
                choices=[("instant", "Od razu"), ("on_request", "Na prośbę")],
                default="instant",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="response_hours",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_request", "Czeka na odpowiedź"),
                    ("pending_payment", "Czeka na wpłatę"),
                    ("confirmed", "Potwierdzona"),
                    ("completed", "Zakończona"),
                    ("canceled", "Anulowana"),
                    ("no_show", "Nieobecność"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentstatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("pending_request", "Czeka na odpowiedź"),
                    ("pending_payment", "Czeka na wpłatę"),
                    ("confirmed", "Potwierdzona"),
                    ("completed", "Zakończona"),
                    ("canceled", "Anulowana"),
                    ("no_show", "Nieobecność"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="RequestRoute",
            fields=[
                ("appointment_id", models.UUIDField(primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField()),
                ("signed_tenant_context", models.TextField()),
                ("due_at", models.DateTimeField()),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("dispatched_at__isnull", True)),
                        fields=["due_at"],
                        name="booking_requestroute_due_idx",
                    )
                ],
            },
        ),
    ]
