# Generated by Django 5.2.17 on 2026-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0031_on_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="balance_due_days_before",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="cancellation_applies_to",
            field=models.CharField(
                choices=[("deposit", "Tylko przedpłata"), ("paid", "Wszystkie wpłaty")],
                default="deposit",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="cancellation_refunds",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
