# Generated by Django 5.2.17 on 2026-10-04 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """A unit as content (ADR-072, slice 5c): whether guests are shown it, its
    address, what it has, its town and coordinates, and its pictures in order
    — new columns of `booking_resource`, already under its tenant policy. And
    an offer's own booking window, for a stay without a season's. Reversible:
    the columns and constraints go away again."""

    dependencies = [
        ('booking', '0032_refund_terms_and_balance'),
        ('organizations', '0059_inventory_audit_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='resource',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resource',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_window_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('public_slug', ''), _negated=True), fields=('organization', 'public_slug'), name='booking_resource_public_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('public', False), models.Q(('public_slug', ''), _negated=True), _connector='OR'), name='booking_resource_public_slug_ck'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='booking_resource_coordinates_ck'),
        ),
    ]
