# Generated by Django 5.2.17 on 2026-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0034_price_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="show_exact_location",
            field=models.BooleanField(default=False),
        ),
    ]
