# Generated by Django 5.2.17 on 2026-08-10 18:05

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "slug",
                    models.SlugField(
                        max_length=80,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug może zawierać małe litery, cyfry i pojedyncze łączniki.",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                (
                    "workspace_kind",
                    models.CharField(
                        choices=[("personal", "Osobista"), ("business", "Firmowa")],
                        default="business",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("onboarding", "W trakcie konfiguracji"),
                            ("active", "Aktywna"),
                            ("suspended", "Zawieszona"),
                            ("archived", "Zarchiwizowana"),
                        ],
                        default="onboarding",
                        max_length=16,
                    ),
                ),
                (
                    "default_locale",
                    models.CharField(
                        choices=[("pl", "Polski"), ("en", "English")], default="pl", max_length=10
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Warsaw", max_length=64)),
                (
                    "currency",
                    models.CharField(
                        default="PLN",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Waluta musi być kodem ISO 4217."
                            )
                        ],
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("slug"),
                        name="organizations_slug_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("archived_at__isnull", False), ("status", "archived")),
                            models.Q(
                                models.Q(("status", "archived"), _negated=True),
                                ("archived_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="organizations_archived_at_status_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "customer_kind",
                    models.CharField(
                        choices=[("person", "Osoba"), ("company", "Firma")],
                        default="company",
                        max_length=16,
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("tax_id", models.CharField(blank=True, max_length=32)),
                (
                    "country_code",
                    models.CharField(
                        default="PL",
                        max_length=2,
                        validators=[django.core.validators.RegexValidator("^[A-Z]{2}$")],
                    ),
                ),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("external_customer_id", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_profile",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=80)),
                (
                    "scope",
                    models.CharField(
                        choices=[("system", "Systemowa"), ("organization", "Organizacyjna")],
                        max_length=16,
                    ),
                ),
                ("permissions", models.JSONField(default=list)),
                ("is_immutable", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("scope", "key"),
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktywne"),
                            ("suspended", "Zawieszone"),
                            ("revoked", "Odebrane"),
                            ("left", "Zakończone przez użytkownika"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="organizations.role",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "user_id", "-created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("key",),
                name="organizations_role_system_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "key"),
                name="organizations_role_org_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_immutable", True), ("organization__isnull", True), ("scope", "system")
                    ),
                    models.Q(("organization__isnull", False), ("scope", "organization")),
                    _connector="OR",
                ),
                name="organizations_role_scope_org_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["organization", "status"], name="org_membership_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["active", "suspended"])),
                fields=("organization", "user"),
                name="organizations_membership_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", False), ("status__in", ["revoked", "left"])),
                    models.Q(("status__in", ["active", "suspended"]), ("revoked_at__isnull", True)),
                    _connector="OR",
                ),
                name="organizations_membership_revoked_at_ck",
            ),
        ),
    ]
