# Generated by Django 5.2.17 on 2026-08-10 18:40

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_refine_manager_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("accepted", "Przyjęte"),
                            ("revoked", "Wycofane"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_organization_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_organization_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="organizations.role",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "expires_at"],
                        name="org_invite_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        models.F("organization"),
                        condition=models.Q(("status", "pending")),
                        name="org_invite_pending_email_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("accepted_at__isnull", True),
                                ("accepted_by__isnull", True),
                                ("revoked_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("accepted_at__isnull", False),
                                ("accepted_by__isnull", False),
                                ("revoked_at__isnull", True),
                                ("status", "accepted"),
                            ),
                            models.Q(
                                ("accepted_at__isnull", True),
                                ("accepted_by__isnull", True),
                                ("revoked_at__isnull", False),
                                ("status", "revoked"),
                            ),
                            _connector="OR",
                        ),
                        name="org_invite_terminal_state_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("organization.created", "Utworzono organizację"),
                            ("organization.updated", "Zmieniono organizację"),
                            ("organization.archived", "Zarchiwizowano organizację"),
                            ("invitation.created", "Utworzono zaproszenie"),
                            ("invitation.revoked", "Wycofano zaproszenie"),
                            ("invitation.accepted", "Przyjęto zaproszenie"),
                            ("membership.role_changed", "Zmieniono rolę członka"),
                            ("membership.suspended", "Zawieszono członka"),
                            ("membership.resumed", "Wznowiono członka"),
                            ("membership.revoked", "Odebrano dostęp członkowi"),
                            ("membership.left", "Członek opuścił organizację"),
                            ("ownership.transferred", "Przeniesiono własność"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "occurred_at"], name="org_audit_occurred_idx"
                    ),
                    models.Index(
                        fields=["organization", "action", "occurred_at"],
                        name="org_audit_action_idx",
                    ),
                ],
            },
        ),
    ]
