# Generated by Django 5.2.17 on 2026-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_protect_system_roles"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="billingprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_customer_id", ""), _negated=True),
                fields=("external_customer_id",),
                name="org_billing_external_customer_uq",
            ),
        ),
    ]
