# Generated by Django 5.2.17 on 2026-08-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationauditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("organization.created", "Utworzono organizację"),
                    ("organization.updated", "Zmieniono organizację"),
                    ("organization.archived", "Zarchiwizowano organizację"),
                    ("invitation.created", "Utworzono zaproszenie"),
                    ("invitation.revoked", "Wycofano zaproszenie"),
                    ("invitation.accepted", "Przyjęto zaproszenie"),
                    ("membership.role_changed", "Zmieniono rolę członka"),
                    ("membership.suspended", "Zawieszono członka"),
                    ("membership.resumed", "Wznowiono członka"),
                    ("membership.revoked", "Odebrano dostęp członkowi"),
                    ("membership.left", "Członek opuścił organizację"),
                    ("ownership.transferred", "Przeniesiono własność"),
                    ("billing.checkout.created", "Utworzono Checkout"),
                    ("billing.portal.created", "Utworzono sesję portalu"),
                    ("billing.trial.started", "Rozpoczęto trial"),
                    ("billing.access.read_only", "Włączono tryb tylko do odczytu"),
                ],
                max_length=64,
            ),
        ),
    ]
