# Generated by Django 5.2.17 on 2026-08-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0016_alter_organizationauditentry_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationauditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("organization.created", "Utworzono organizację"),
                    ("organization.updated", "Zmieniono organizację"),
                    ("organization.archived", "Zarchiwizowano organizację"),
                    ("invitation.created", "Utworzono zaproszenie"),
                    ("invitation.revoked", "Wycofano zaproszenie"),
                    ("invitation.accepted", "Przyjęto zaproszenie"),
                    ("membership.role_changed", "Zmieniono rolę członka"),
                    ("membership.suspended", "Zawieszono członka"),
                    ("membership.resumed", "Wznowiono członka"),
                    ("membership.revoked", "Odebrano dostęp członkowi"),
                    ("membership.left", "Członek opuścił organizację"),
                    ("ownership.transferred", "Przeniesiono własność"),
                    ("billing.checkout.created", "Utworzono Checkout"),
                    ("billing.portal.created", "Utworzono sesję portalu"),
                    ("billing.trial.started", "Rozpoczęto trial"),
                    ("billing.access.read_only", "Włączono tryb tylko do odczytu"),
                    ("billing.reconciled", "Naprawiono stan billingowy"),
                    ("billing.override.created", "Utworzono override dostępu"),
                    ("billing.override.revoked", "Wycofano override dostępu"),
                    ("billing.override.expired", "Wygasł override dostępu"),
                    ("support.notification.retried", "Ponowiono wiadomość"),
                    ("support.webhook.retried", "Ponowiono webhook"),
                    ("integration.api_key.created", "Utworzono klucz API"),
                    ("integration.api_key.rotated", "Obrócono klucz API"),
                    ("integration.api_key.revoked", "Wycofano klucz API"),
                    ("integration.webhook.created", "Utworzono webhook"),
                ],
                max_length=64,
            ),
        ),
    ]
