# Generated by Django 5.2.17 on 2026-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0045_audit_profile_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationauditentry",
            name="channel",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="organizationauditentry",
            name="credential_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
