# Generated by Django 5.2.17 on 2026-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0051_audit_crews_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationauditentry",
            name="acting_via",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="organizationauditentry",
            name="acting_ref",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="organizationauditentry",
            name="acting_trigger",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
