# Generated by Django 5.2.17 on 2026-10-02 18:00

from typing import Any

import django.contrib.postgres.fields
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models

import saas_core.modules.core.organizations.models


def fill_public_locales(apps: Any, schema_editor: Any) -> None:
    """Existing companies speak to customers in their own language; the
    deployment's publisher in every language of the profile (ADR-071 pkt 4).

    Runs as the table owner, so FORCE RLS does not hide other tenants' rows.
    The modules append the languages their content already has in their own
    migrations — core does not know them.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE organizations_organization "
            "SET public_locales = ARRAY[default_locale]::varchar(10)[] "
            "WHERE workspace_kind <> 'platform' AND default_locale ~ '^[a-z]{2}$'"
        )
        cursor.execute(
            "UPDATE organizations_organization SET public_locales = %s::varchar(10)[] "
            "WHERE workspace_kind = 'platform'",
            [list(settings.SITES_SUPPORTED_LOCALES)],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0052_audit_acting"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_locales",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                default=saas_core.modules.core.organizations.models.default_public_locales,
                size=None,
            ),
        ),
        migrations.RunPython(fill_public_locales, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(("public_locales__len__gte", 1)),
                name="organizations_public_locales_nonempty_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Regex(
                    models.Func(
                        models.F("public_locales"),
                        models.Value(","),
                        function="array_to_string",
                        output_field=models.TextField(),
                    ),
                    "^[a-z]{2}(,[a-z]{2})*$",
                ),
                name="organizations_public_locales_format_ck",
            ),
        ),
    ]
