# Generated by Django 5.2.17 on 2026-10-02 20:57

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The history of the company's languages (ADR-071 pkt 5): written and read
# inside the tenant, so forced row-level security like every private tenant
# table.
FORWARD_SQL = """
ALTER TABLE organizations_publiclocaleschange ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations_publiclocaleschange FORCE ROW LEVEL SECURITY;
CREATE POLICY organizations_publiclocaleschange_tenant_isolation
ON organizations_publiclocaleschange
USING (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid);
"""

REVERSE_SQL = """
DROP POLICY organizations_publiclocaleschange_tenant_isolation
ON organizations_publiclocaleschange;
ALTER TABLE organizations_publiclocaleschange NO FORCE ROW LEVEL SECURITY;
ALTER TABLE organizations_publiclocaleschange DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0054_command_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_locales_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organizationauditentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("organization.created", "Utworzono organizację"),
                    ("organization.updated", "Zmieniono organizację"),
                    ("organization.archived", "Zarchiwizowano organizację"),
                    ("organization.settings_changed", "Zmieniono ustawienia"),
                    ("invitation.created", "Utworzono zaproszenie"),
                    ("invitation.revoked", "Wycofano zaproszenie"),
                    ("invitation.accepted", "Przyjęto zaproszenie"),
                    ("membership.role_changed", "Zmieniono rolę członka"),
                    ("membership.suspended", "Zawieszono członka"),
                    ("membership.resumed", "Wznowiono członka"),
                    ("membership.revoked", "Odebrano dostęp członkowi"),
                    ("membership.left", "Członek opuścił organizację"),
                    ("ownership.transferred", "Przeniesiono własność"),
                    ("role.created", "Utworzono rolę"),
                    ("role.updated", "Zmieniono rolę"),
                    ("role.deleted", "Usunięto rolę"),
                    ("farms.farm.created", "Dodano gospodarstwo"),
                    ("farms.farm.updated", "Zmieniono gospodarstwo"),
                    ("farms.animal.created", "Dodano zwierzę"),
                    ("farms.animal.updated", "Zmieniono zwierzę"),
                    ("farms.activation_code.issued", "Wydano kod aktywacji gospodarstwa"),
                    ("farms.farm.taken_over", "Rolnik przejął gospodarstwo"),
                    ("farms.share.granted", "Udostępniono gospodarstwo firmie"),
                    ("farms.share.revoked", "Cofnięto udostępnienie gospodarstwa"),
                    ("farms.share.changed", "Zmieniono zakres udostępnienia gospodarstwa"),
                    ("farms.animal.health_recorded", "Dopisano wpis w kartotece zwierzęcia"),
                    ("farms.animal.health_corrected", "Poprawiono wpis w kartotece zwierzęcia"),
                    ("farms.herd.pushed", "Wysłano stado do rejestru rolnika"),
                    ("inventory.item.created", "Dodano pozycję magazynu"),
                    ("inventory.item.updated", "Zmieniono pozycję magazynu"),
                    ("inventory.category.created", "Dodano kategorię magazynu"),
                    ("inventory.category.updated", "Zmieniono kategorię magazynu"),
                    ("inventory.category.deleted", "Usunięto kategorię magazynu"),
                    ("inventory.location.created", "Dodano magazyn"),
                    ("inventory.location.updated", "Zmieniono magazyn"),
                    ("inventory.supplier.created", "Dodano dostawcę"),
                    ("inventory.supplier.updated", "Zmieniono dostawcę"),
                    ("inventory.document.posted", "Zatwierdzono dokument magazynowy"),
                    ("inventory.document.corrected", "Skorygowano dokument magazynowy"),
                    ("billing.profile.updated", "Zmieniono dane do faktury"),
                    ("billing.checkout.created", "Utworzono Checkout"),
                    ("billing.portal.created", "Utworzono sesję portalu"),
                    ("billing.trial.started", "Rozpoczęto trial"),
                    ("billing.access.read_only", "Włączono tryb tylko do odczytu"),
                    ("billing.reconciled", "Naprawiono stan billingowy"),
                    ("billing.override.created", "Utworzono override dostępu"),
                    ("billing.override.revoked", "Wycofano override dostępu"),
                    ("billing.override.expired", "Wygasł override dostępu"),
                    ("billing.credits.purchased", "Kupiono kredyty"),
                    ("billing.credits.adjusted", "Skorygowano kredyty"),
                    ("support.notification.retried", "Ponowiono wiadomość"),
                    ("support.webhook.retried", "Ponowiono webhook"),
                    ("integration.api_key.created", "Utworzono klucz API"),
                    ("integration.api_key.rotated", "Obrócono klucz API"),
                    ("integration.api_key.revoked", "Wycofano klucz API"),
                    ("integration.webhook.created", "Utworzono webhook"),
                    ("booking.catalog.changed", "Zmieniono katalog rezerwacji"),
                    ("profile.created", "Utworzono profil publiczny"),
                    ("profile.updated", "Zmieniono profil publiczny"),
                    ("profile.deleted", "Usunięto profil publiczny"),
                    ("profile.published", "Włączono wizytówkę w katalogu"),
                    ("profile.withdrawn", "Wyłączono wizytówkę z katalogu"),
                    ("booking.schedule.changed", "Zmieniono grafik rezerwacji"),
                    ("booking.appointment.created", "Utworzono rezerwację"),
                    ("booking.appointment.rescheduled", "Zmieniono termin rezerwacji"),
                    ("booking.appointment.canceled", "Anulowano rezerwację"),
                    ("booking.appointment.completed", "Zakończono wizytę"),
                    ("booking.appointment.materials_changed", "Zmieniono produkty wizyty"),
                    ("booking.customer.anonymized", "Zanonimizowano klienta"),
                    ("booking.staff.added", "Dodano pracownika"),
                    ("booking.staff.updated", "Zmieniono dane pracownika"),
                    ("booking.staff.linked", "Połączono pracownika z kontem"),
                    ("booking.staff.services_changed", "Zmieniono usługi pracownika"),
                    ("booking.staff.hours_changed", "Zmieniono godziny pracy"),
                    ("booking.staff.time_off_added", "Dodano nieobecność"),
                    ("booking.staff.time_off_removed", "Usunięto nieobecność"),
                    ("booking.staff.ended", "Zakończono współpracę"),
                    ("booking.staff.restored", "Przywrócono pracownika"),
                    (
                        "booking.staff.public_changed",
                        "Zmieniono widoczność pracownika dla klientów",
                    ),
                    ("booking.team.created", "Utworzono zespół"),
                    ("booking.team.updated", "Zmieniono zespół"),
                    ("booking.team.deleted", "Usunięto zespół"),
                    ("booking.appointment.crew_changed", "Zmieniono skład wizyty"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="PublicLocalesChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                (
                    "before",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), size=None
                    ),
                ),
                (
                    "after",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), size=None
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("settings", "Ustawienia"), ("site_source", "Język nowej strony")],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "idempotency_key"),
                        name="organizations_public_locales_change_idem_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "version"),
                        name="organizations_public_locales_change_version_uq",
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
