# Generated by Django 5.2.17 on 2026-10-02 21:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# A company's settings and the receipts of their changes (ADR-078 pkt 7):
# written and read only inside the tenant, so forced row-level security like
# every private tenant table.
TABLES = ("organizations_organizationsetting", "organizations_organizationsettingsreceipt")
FORWARD_SQL = "".join(
    f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {table}_tenant_isolation ON {table}
USING (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid);
"""
    for table in TABLES
)
REVERSE_SQL = "".join(
    f"""
DROP POLICY {table}_tenant_isolation ON {table};
ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
"""
    for table in TABLES
)


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0055_public_locales_change"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("value", models.JSONField(null=True)),
                ("version", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "key"), name="organizations_setting_key_uq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettingsReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("group", models.CharField(max_length=120)),
                ("principal_ref", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "group", "principal_ref", "idempotency_key"),
                        name="organizations_settings_receipt_uq",
                    )
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
