from django.urls import path

from .price_views import (
    ExtraCreatePreviewView,
    ExtraDetailView,
    ExtraListView,
    ExtraUpdatePreviewView,
    ParticipantCategoryCreatePreviewView,
    ParticipantCategoryDetailView,
    ParticipantCategoryListView,
    ParticipantCategoryUpdatePreviewView,
    PriceRuleCopyYearPreviewView,
    PriceRuleCopyYearView,
    PriceRuleCreatePreviewView,
    PriceRuleDetailView,
    PriceRuleListView,
    PriceRuleUpdatePreviewView,
)
from .translation_views import (
    ItemTranslationListView,
    ItemTranslationPreviewView,
    ItemTranslationView,
)
from .views import (
    AppointmentAcceptView,
    AppointmentCancelView,
    AppointmentCandidatesView,
    AppointmentCompleteView,
    AppointmentCrewView,
    AppointmentDeclineView,
    AppointmentListCreateView,
    AppointmentMaterialsView,
    AppointmentNoShowView,
    AppointmentPlaceView,
    AppointmentRescheduleView,
    BookingCatalogView,
    BookingClosureCopyYearPreviewView,
    BookingClosureCopyYearView,
    BookingClosureCreatePreviewView,
    BookingClosureDetailView,
    BookingClosureListView,
    BookingClosureUpdatePreviewView,
    BookingOccupancyView,
    BookingOverviewView,
    BookingPlacesView,
    BookingPresetListView,
    BookingQueueView,
    BookingQuoteView,
    BookingRuleCopyYearPreviewView,
    BookingRuleCopyYearView,
    BookingRuleCreatePreviewView,
    BookingRuleDetailView,
    BookingRuleListView,
    BookingRuleUpdatePreviewView,
    BookingScheduleView,
    BookingSetupOptionsView,
    BookingSetupView,
    BookingSlotDaysView,
    BookingSlotsView,
    BookingSlotTimesView,
    CustomerAnonymizeView,
    PerformanceView,
    PublicBookingCatalogView,
    PublicBookingConsentsView,
    PublicBookingCreateView,
    PublicBookingDaysView,
    PublicBookingQuoteView,
    PublicBookingSlotsView,
    PublicBookingTimesView,
    SelfServiceAppointmentView,
    SelfServiceCancelView,
    SelfServiceRescheduleView,
    ServiceMaterialsView,
    SetupGroupCreatePreviewView,
    SetupGroupDetailView,
    SetupGroupListView,
    SetupGroupUpdatePreviewView,
    SetupLocationCreatePreviewView,
    SetupLocationDetailView,
    SetupLocationListView,
    SetupLocationUpdatePreviewView,
    SetupResourceCreatePreviewView,
    SetupResourceDetailView,
    SetupResourceListView,
    SetupResourceUpdatePreviewView,
    SetupServiceCreatePreviewView,
    SetupServiceDetailView,
    SetupServiceListView,
    SetupServiceUpdatePreviewView,
    StaffAvailabilityView,
    StaffDetailView,
    StaffEndView,
    StaffFactsView,
    StaffHistoryView,
    StaffHoursPreviewView,
    StaffHoursView,
    StaffInvitationView,
    StaffListView,
    StaffPublicView,
    StaffRestoreView,
    StaffServicesView,
    StaffTimeOffView,
    StayCreateView,
    StayEndsView,
    StayMovePreviewView,
    StayMoveView,
    StayPreviewView,
    StayStartsView,
    TeamDetailView,
    TeamListView,
    TimeOffDetailView,
    UnitBlockDetailView,
    UnitBlockListView,
    UnitBlockPreviewView,
)

app_name = "booking"

urlpatterns = [
    path("catalog/", BookingCatalogView.as_view(), name="catalog"),
    path("staff/", StaffListView.as_view(), name="staff-list"),
    path("staff/<uuid:staff_id>/", StaffDetailView.as_view(), name="staff"),
    path("staff/<uuid:staff_id>/services/", StaffServicesView.as_view(), name="staff-services"),
    path("staff/<uuid:staff_id>/hours/", StaffHoursView.as_view(), name="staff-hours"),
    path(
        "staff/<uuid:staff_id>/hours/preview/",
        StaffHoursPreviewView.as_view(),
        name="staff-hours-preview",
    ),
    path("staff/<uuid:staff_id>/time-off/", StaffTimeOffView.as_view(), name="staff-time-off"),
    path(
        "staff/<uuid:staff_id>/invitation/", StaffInvitationView.as_view(), name="staff-invitation"
    ),
    path("staff/<uuid:staff_id>/end/", StaffEndView.as_view(), name="staff-end"),
    path("staff/<uuid:staff_id>/restore/", StaffRestoreView.as_view(), name="staff-restore"),
    path("staff/<uuid:staff_id>/public/", StaffPublicView.as_view(), name="staff-public"),
    path("staff/<uuid:staff_id>/facts/", StaffFactsView.as_view(), name="staff-facts"),
    path("staff/<uuid:staff_id>/history/", StaffHistoryView.as_view(), name="staff-history"),
    path("time-off/<uuid:time_off_id>/", TimeOffDetailView.as_view(), name="time-off"),
    path("staff-availability/", StaffAvailabilityView.as_view(), name="staff-availability"),
    path("teams/", TeamListView.as_view(), name="teams"),
    path("teams/<uuid:team_id>/", TeamDetailView.as_view(), name="team"),
    path("queue/", BookingQueueView.as_view(), name="queue"),
    path("overview/", BookingOverviewView.as_view(), name="overview"),
    path("performance/", PerformanceView.as_view(), name="performance"),
    path(
        "appointments/<uuid:appointment_id>/candidates/",
        AppointmentCandidatesView.as_view(),
        name="candidates",
    ),
    path(
        "appointments/<uuid:appointment_id>/crew/",
        AppointmentCrewView.as_view(),
        name="crew",
    ),
    path("schedule/", BookingScheduleView.as_view(), name="schedule"),
    path("setup/", BookingSetupView.as_view(), name="setup"),
    path("setup/options/", BookingSetupOptionsView.as_view(), name="setup-options"),
    path("presets/", BookingPresetListView.as_view(), name="presets"),
    path(
        "setup/translations/<str:kind>/<uuid:item_id>/",
        ItemTranslationListView.as_view(),
        name="setup-item-translations",
    ),
    path(
        "setup/translations/<str:kind>/<uuid:item_id>/<slug:locale>/",
        ItemTranslationView.as_view(),
        name="setup-item-translation",
    ),
    path(
        "setup/translations/<str:kind>/<uuid:item_id>/<slug:locale>/preview/",
        ItemTranslationPreviewView.as_view(),
        name="setup-item-translation-preview",
    ),
    path("setup/services/", SetupServiceListView.as_view(), name="setup-services"),
    path(
        "setup/services/preview/",
        SetupServiceCreatePreviewView.as_view(),
        name="setup-services-preview",
    ),
    path(
        "setup/services/<uuid:service_id>/",
        SetupServiceDetailView.as_view(),
        name="setup-service",
    ),
    path(
        "setup/services/<uuid:service_id>/preview/",
        SetupServiceUpdatePreviewView.as_view(),
        name="setup-service-preview",
    ),
    path("setup/locations/", SetupLocationListView.as_view(), name="setup-locations"),
    path(
        "setup/locations/preview/",
        SetupLocationCreatePreviewView.as_view(),
        name="setup-locations-preview",
    ),
    path(
        "setup/locations/<uuid:location_id>/",
        SetupLocationDetailView.as_view(),
        name="setup-location",
    ),
    path(
        "setup/locations/<uuid:location_id>/preview/",
        SetupLocationUpdatePreviewView.as_view(),
        name="setup-location-preview",
    ),
    path("setup/resources/", SetupResourceListView.as_view(), name="setup-resources"),
    path(
        "setup/resources/preview/",
        SetupResourceCreatePreviewView.as_view(),
        name="setup-resources-preview",
    ),
    path(
        "setup/resources/<uuid:resource_id>/",
        SetupResourceDetailView.as_view(),
        name="setup-resource",
    ),
    path(
        "setup/resources/<uuid:resource_id>/preview/",
        SetupResourceUpdatePreviewView.as_view(),
        name="setup-resource-preview",
    ),
    path(
        "setup/resources/<uuid:resource_id>/blocks/",
        UnitBlockListView.as_view(),
        name="unit-blocks",
    ),
    path(
        "setup/resources/<uuid:resource_id>/blocks/preview/",
        UnitBlockPreviewView.as_view(),
        name="unit-blocks-preview",
    ),
    path("setup/blocks/<uuid:block_id>/", UnitBlockDetailView.as_view(), name="unit-block"),
    path("occupancy/", BookingOccupancyView.as_view(), name="occupancy"),
    path("stays/", StayCreateView.as_view(), name="stays"),
    path("stays/preview/", StayPreviewView.as_view(), name="stays-preview"),
    path("stays/starts/", StayStartsView.as_view(), name="stay-starts"),
    path("stays/ends/", StayEndsView.as_view(), name="stay-ends"),
    path(
        "appointments/<uuid:appointment_id>/stay/",
        StayMoveView.as_view(),
        name="stay-move",
    ),
    path(
        "appointments/<uuid:appointment_id>/stay/preview/",
        StayMovePreviewView.as_view(),
        name="stay-move-preview",
    ),
    path("setup/rules/", BookingRuleListView.as_view(), name="rules"),
    path("setup/rules/preview/", BookingRuleCreatePreviewView.as_view(), name="rules-preview"),
    path("setup/rules/copy-year/", BookingRuleCopyYearView.as_view(), name="rules-copy-year"),
    path(
        "setup/rules/copy-year/preview/",
        BookingRuleCopyYearPreviewView.as_view(),
        name="rules-copy-year-preview",
    ),
    path("setup/rules/<uuid:rule_id>/", BookingRuleDetailView.as_view(), name="rule"),
    path(
        "setup/rules/<uuid:rule_id>/preview/",
        BookingRuleUpdatePreviewView.as_view(),
        name="rule-preview",
    ),
    path("quote/", BookingQuoteView.as_view(), name="quote"),
    path("setup/prices/", PriceRuleListView.as_view(), name="prices"),
    path("setup/prices/preview/", PriceRuleCreatePreviewView.as_view(), name="prices-preview"),
    path("setup/prices/copy-year/", PriceRuleCopyYearView.as_view(), name="prices-copy-year"),
    path(
        "setup/prices/copy-year/preview/",
        PriceRuleCopyYearPreviewView.as_view(),
        name="prices-copy-year-preview",
    ),
    path("setup/prices/<uuid:price_id>/", PriceRuleDetailView.as_view(), name="price"),
    path(
        "setup/prices/<uuid:price_id>/preview/",
        PriceRuleUpdatePreviewView.as_view(),
        name="price-preview",
    ),
    path("setup/extras/", ExtraListView.as_view(), name="extras"),
    path("setup/extras/preview/", ExtraCreatePreviewView.as_view(), name="extras-preview"),
    path("setup/extras/<uuid:extra_id>/", ExtraDetailView.as_view(), name="extra"),
    path(
        "setup/extras/<uuid:extra_id>/preview/",
        ExtraUpdatePreviewView.as_view(),
        name="extra-preview",
    ),
    path(
        "setup/participant-categories/",
        ParticipantCategoryListView.as_view(),
        name="participant-categories",
    ),
    path(
        "setup/participant-categories/preview/",
        ParticipantCategoryCreatePreviewView.as_view(),
        name="participant-categories-preview",
    ),
    path(
        "setup/participant-categories/<uuid:category_id>/",
        ParticipantCategoryDetailView.as_view(),
        name="participant-category",
    ),
    path(
        "setup/participant-categories/<uuid:category_id>/preview/",
        ParticipantCategoryUpdatePreviewView.as_view(),
        name="participant-category-preview",
    ),
    path("setup/closures/", BookingClosureListView.as_view(), name="closures"),
    path(
        "setup/closures/preview/",
        BookingClosureCreatePreviewView.as_view(),
        name="closures-preview",
    ),
    path(
        "setup/closures/copy-year/",
        BookingClosureCopyYearView.as_view(),
        name="closures-copy-year",
    ),
    path(
        "setup/closures/copy-year/preview/",
        BookingClosureCopyYearPreviewView.as_view(),
        name="closures-copy-year-preview",
    ),
    path("setup/closures/<uuid:closure_id>/", BookingClosureDetailView.as_view(), name="closure"),
    path(
        "setup/closures/<uuid:closure_id>/preview/",
        BookingClosureUpdatePreviewView.as_view(),
        name="closure-preview",
    ),
    path("setup/groups/", SetupGroupListView.as_view(), name="setup-groups"),
    path(
        "setup/groups/preview/",
        SetupGroupCreatePreviewView.as_view(),
        name="setup-groups-preview",
    ),
    path("setup/groups/<uuid:group_id>/", SetupGroupDetailView.as_view(), name="setup-group"),
    path(
        "setup/groups/<uuid:group_id>/preview/",
        SetupGroupUpdatePreviewView.as_view(),
        name="setup-group-preview",
    ),
    path("slots/", BookingSlotsView.as_view(), name="slots"),
    path("slots/days/", BookingSlotDaysView.as_view(), name="slot-days"),
    path("slots/times/", BookingSlotTimesView.as_view(), name="slot-times"),
    path("appointments/", AppointmentListCreateView.as_view(), name="appointments"),
    path(
        "appointments/<uuid:appointment_id>/reschedule/",
        AppointmentRescheduleView.as_view(),
        name="reschedule",
    ),
    path(
        "appointments/<uuid:appointment_id>/cancel/", AppointmentCancelView.as_view(), name="cancel"
    ),
    path(
        "appointments/<uuid:appointment_id>/accept/",
        AppointmentAcceptView.as_view(),
        name="accept-request",
    ),
    path(
        "appointments/<uuid:appointment_id>/decline/",
        AppointmentDeclineView.as_view(),
        name="decline-request",
    ),
    path(
        "appointments/<uuid:appointment_id>/complete/",
        AppointmentCompleteView.as_view(),
        name="complete",
    ),
    path(
        "appointments/<uuid:appointment_id>/no-show/",
        AppointmentNoShowView.as_view(),
        name="no-show",
    ),
    path(
        "appointments/<uuid:appointment_id>/materials/",
        AppointmentMaterialsView.as_view(),
        name="appointment-materials",
    ),
    path(
        "appointments/<uuid:appointment_id>/place/",
        AppointmentPlaceView.as_view(),
        name="appointment-place",
    ),
    path("places/", BookingPlacesView.as_view(), name="places"),
    path(
        "catalog/services/<uuid:service_id>/materials/",
        ServiceMaterialsView.as_view(),
        name="service-materials",
    ),
    path(
        "customers/<uuid:customer_id>/anonymize/",
        CustomerAnonymizeView.as_view(),
        name="customer-anonymize",
    ),
    path("public/<slug:public_slug>/", PublicBookingCatalogView.as_view(), name="public-catalog"),
    path(
        "public/<slug:public_slug>/consents/",
        PublicBookingConsentsView.as_view(),
        name="public-consents",
    ),
    path("public/<slug:public_slug>/slots/", PublicBookingSlotsView.as_view(), name="public-slots"),
    path("public/<slug:public_slug>/days/", PublicBookingDaysView.as_view(), name="public-days"),
    path("public/<slug:public_slug>/times/", PublicBookingTimesView.as_view(), name="public-times"),
    path("public/<slug:public_slug>/quote/", PublicBookingQuoteView.as_view(), name="public-quote"),
    path(
        "public/<slug:public_slug>/appointments/",
        PublicBookingCreateView.as_view(),
        name="public-create",
    ),
    path("self-service/<str:token>/", SelfServiceAppointmentView.as_view(), name="self-service"),
    path(
        "self-service/<str:token>/reschedule/",
        SelfServiceRescheduleView.as_view(),
        name="self-reschedule",
    ),
    path("self-service/<str:token>/cancel/", SelfServiceCancelView.as_view(), name="self-cancel"),
]
