# Generated by Django 5.2.17 on 2026-08-10 16:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "Sukces"),
                    ("mfa_required", "Wymagany drugi składnik"),
                    ("mfa_setup", "Wymagana konfiguracja MFA"),
                    ("invalid", "Nieprawidłowe dane"),
                    ("inactive", "Konto nieaktywne"),
                    ("rate_limited", "Limit prób"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="UserMfaMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[("totp", "Aplikacja uwierzytelniająca")],
                        default="totp",
                        max_length=16,
                    ),
                ),
                ("secret_ciphertext", models.TextField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_counter", models.BigIntegerField(default=-1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_method",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user_id",),
            },
        ),
        migrations.CreateModel(
            name="MfaRecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to="identity.usermfamethod",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(fields=["method", "used_at"], name="identity_mfa_recovery_idx")
                ],
            },
        ),
    ]
