# Generated by Django 5.2.17 on 2026-08-10 17:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_alter_loginattempt_outcome_usermfamethod_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("email_verified", "Potwierdzono adres e-mail"),
                            ("password_reset", "Zmieniono hasło przez reset"),
                            ("mfa_enabled", "Włączono MFA"),
                            ("session_revoked", "Unieważniono sesję"),
                        ],
                        max_length=32,
                    ),
                ),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_account_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["subject_user", "occurred_at"], name="identity_audit_subject_idx"
                    ),
                    models.Index(
                        fields=["event_type", "occurred_at"], name="identity_audit_type_idx"
                    ),
                ],
            },
        ),
    ]
