# Generated by Django 5.2.17 on 2026-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_accountauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="accountauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("email_verified", "Potwierdzono adres e-mail"),
                    ("password_reset", "Zmieniono hasło przez reset"),
                    ("mfa_enabled", "Włączono MFA"),
                    ("session_revoked", "Unieważniono sesję"),
                    ("profile_updated", "Zmieniono dane osobowe"),
                ],
                max_length=32,
            ),
        ),
    ]
