# Generated by Django 5.2.17 on 2026-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0005_operator_grant"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountauditevent",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="accountauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("email_verified", "Potwierdzono adres e-mail"),
                    ("password_reset", "Zmieniono hasło przez reset"),
                    ("mfa_enabled", "Włączono MFA"),
                    ("mfa_reset", "Zresetowano MFA operatora"),
                    ("session_revoked", "Unieważniono sesję"),
                    ("profile_updated", "Zmieniono dane osobowe"),
                ],
                max_length=32,
            ),
        ),
    ]
