# Generated by Django 5.2.17 on 2026-10-03 21:15

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # A consent points at a customer, and the customer's table is the one
        # booking's migrations made (ADR-073 §2).
        ("booking", "0029_customer_to_customers"),
        ("customers", "0001_customer_state"),
        ("organizations", "0059_inventory_audit_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRoute",
            fields=[
                ("public_id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField()),
                ("document_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking_terms", "Regulamin rezerwacji"),
                            ("shop_terms", "Regulamin sklepu"),
                            ("privacy_policy", "Polityka prywatności"),
                            ("cancellation_policy", "Polityka anulowania"),
                        ],
                        max_length=32,
                    ),
                ),
                ("draft_text", models.TextField(blank=True)),
                ("draft_locale", models.CharField(blank=True, max_length=10)),
                ("draft_origin_ref", models.CharField(blank=True, max_length=120)),
                ("version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DocumentText",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("text", models.TextField()),
                ("text_hash", models.CharField(max_length=64)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("accepted_by", models.UUIDField()),
                ("accepted_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("version_id", "locale", "-accepted_at", "-id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "Dokument"),
                            ("marketing", "Zgoda marketingowa"),
                            ("field", "Pole formularza"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text_hash", models.CharField(blank=True, max_length=64)),
                ("locale", models.CharField(blank=True, max_length=10)),
                ("granted", models.BooleanField(default=True)),
                ("source", models.CharField(max_length=64)),
                ("source_reference", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "document_text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="customers.documenttext",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-created_at", "-id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("source_locale", models.CharField(max_length=10)),
                ("effective_from", models.DateField()),
                ("approved_by", models.UUIDField()),
                ("approved_at", models.DateTimeField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="customers.customerdocument",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("document_id", "-number"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="documenttext",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="texts",
                to="customers.documentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerdocument",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind"), name="customers_document_kind_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["organization", "customer"], name="customers_consent_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["organization", "source", "source_reference"],
                name="customers_consent_source_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("document_text__isnull", False), ("kind", "document")),
                    models.Q(
                        models.Q(("kind", "document"), _negated=True),
                        ("document_text__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="customers_consent_document_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "number"), name="customers_documentversion_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_locale__regex", "^[a-z]{2}$")),
                name="customers_documentversion_locale_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttext",
            index=models.Index(
                fields=["version", "locale", "-accepted_at"], name="customers_doctext_current_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttext",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="customers_documenttext_locale_ck",
            ),
        ),
    ]
