# Generated by Django 5.2.17 on 2026-09-17 17:47

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0034_add_gsc_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('keeper_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('housing', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'name', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=40)),
                ('working_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'W stadzie'), ('sold', 'Sprzedane'), ('culled', 'Wybrakowane'), ('dead', 'Padłe')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='hoofcare.farm')),
            ],
            options={
                'ordering': ('organization_id', 'farm_id', 'national_id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='hoofcare_farm_org_name_uq'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['organization', 'national_id'], name='hoofcare_animal_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('organization', 'farm', 'national_id'), name='hoofcare_animal_farm_tag_uq'),
        ),
    ]
