# Generated by Django 5.2.17 on 2026-09-17 18:24

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_service_appointment_kind'),
        ('hoofcare', '0002_rls_and_tenant_guards'),
        ('organizations', '0034_add_gsc_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerdVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herd_visit', to='booking.appointment')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='hoofcare.farm')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', '-created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('arrived_at__isnull', False), _connector='OR'), name='hoofcare_visit_left_needs_arrival_ck')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
