# Generated by Django 5.2.17 on 2026-09-24 13:40

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0048_audit_visit_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("membership_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ingesting", "Ingesting"),
                            ("succeeded", "Succeeded"),
                            ("refused", "Refused"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("aspect", models.CharField(max_length=8)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("model", models.CharField(max_length=80)),
                ("prompt", models.TextField(blank=True)),
                ("prompt_sha256", models.CharField(max_length=64)),
                ("credit_reservation_key", models.CharField(blank=True, max_length=120)),
                ("credit_cost", models.PositiveIntegerField(default=0)),
                ("media_asset_id", models.UUIDField(blank=True, null=True)),
                ("cost_usd_micros", models.BigIntegerField(blank=True, null=True)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "state", "next_attempt_at"],
                        name="imagegen_job_dispatch_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "created_by", "idempotency_key"),
                        name="imagegen_job_org_actor_key_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
