"""Public extension API of the Organizations module."""

from .canonical import canonical_json, canonical_json_hash
from .command_executor import (
    CHANNEL_FEATURES,
    CallResult,
    CommandGate,
    ConsentGroup,
    Invocation,
    Plan,
    execute_plan,
    offer_plan,
    pending_consent,
    preview_plan,
    register_command_gate,
)
from .command_registry import (
    CommandSpec,
    Effect,
    Preview,
    UnknownCommand,
    command,
    command_for_tool,
    command_tools,
    register_command,
    registered_commands,
)
from .currency import register_currency_use
from .events import (
    DomainEvent,
    DomainEventDeliveryError,
    DomainEventHandler,
    dispatch_domain_event,
    register_domain_event_handler,
)
from .history import HistoryTarget, register_history_target
from .identity_facts import OrganizationFacts, organization_facts, register_organization_facts
from .joining import (
    InvitationAcceptedHandler,
    SeatLimit,
    SeatLimitReached,
    register_invitation_accepted,
    register_seat_limit,
)
from .person_gate import PersonRequired, assert_person_required
from .platform_settings import platform_setting
from .public_locales import (
    LocaleRedirect,
    PublicLocalesLimit,
    include_site_source_locale,
    register_public_locales_changed,
    register_public_locales_guard,
    register_public_locales_impact,
    register_public_locales_limit,
)
from .references import (
    ResourceReferenceConflict,
    ResourceReferenceHandler,
    ResourceReferenceRejected,
    copy_resource_references,
    list_resource_reference_ids,
    record_resource_references,
    register_resource_reference_handler,
)
from .retention import GRACE_DAYS as RETENTION_GRACE_DAYS
from .retention import OFF as RETENTION_OFF
from .retention import PERIODS as RETENTION_PERIODS
from .retention import (
    RetentionSweep,
    company_months,
    cutoff_for,
    excluded_ids,
    held_back,
    months_of,
    platform_days,
    register_retention_exclusion,
    register_retention_sweep,
)
from .retention import Rule as RetentionRule
from .service_scopes import register_service_scope
from .settings_commands import group_commands
from .settings_registry import (
    SettingArea,
    SettingGroup,
    SettingSpec,
    has_link,
    register_setting_area,
    register_setting_group,
    relabel_settings,
    relabeled_group_keys,
    schema_entry,
    unrelabeled_group,
)
from .settings_service import (
    Resolved,
    change_settings,
    inherited,
    register_settings_feature_check,
    resolve,
    setting,
    settings_snapshot,
    validate_settings,
)

__all__ = [
    "RETENTION_GRACE_DAYS",
    "RETENTION_OFF",
    "RETENTION_PERIODS",
    "RetentionRule",
    "RetentionSweep",
    "company_months",
    "cutoff_for",
    "excluded_ids",
    "held_back",
    "months_of",
    "platform_days",
    "register_retention_exclusion",
    "register_retention_sweep",
    "register_service_scope",
    "HistoryTarget",
    "register_history_target",
    "Resolved",
    "SettingArea",
    "SettingGroup",
    "SettingSpec",
    "change_settings",
    "group_commands",
    "has_link",
    "inherited",
    "platform_setting",
    "register_setting_area",
    "register_setting_group",
    "relabel_settings",
    "relabeled_group_keys",
    "register_settings_feature_check",
    "resolve",
    "setting",
    "settings_snapshot",
    "schema_entry",
    "unrelabeled_group",
    "validate_settings",
    "CHANNEL_FEATURES",
    "CallResult",
    "CommandGate",
    "CommandSpec",
    "ConsentGroup",
    "Plan",
    "DomainEvent",
    "DomainEventDeliveryError",
    "DomainEventHandler",
    "Effect",
    "InvitationAcceptedHandler",
    "LocaleRedirect",
    "Invocation",
    "Preview",
    "PersonRequired",
    "PublicLocalesLimit",
    "ResourceReferenceConflict",
    "ResourceReferenceHandler",
    "ResourceReferenceRejected",
    "SeatLimit",
    "SeatLimitReached",
    "UnknownCommand",
    "assert_person_required",
    "canonical_json",
    "canonical_json_hash",
    "command",
    "command_for_tool",
    "command_tools",
    "copy_resource_references",
    "include_site_source_locale",
    "execute_plan",
    "offer_plan",
    "pending_consent",
    "preview_plan",
    "dispatch_domain_event",
    "list_resource_reference_ids",
    "record_resource_references",
    "register_command",
    "register_command_gate",
    "register_domain_event_handler",
    "register_invitation_accepted",
    "OrganizationFacts",
    "organization_facts",
    "register_organization_facts",
    "register_public_locales_changed",
    "register_currency_use",
    "register_public_locales_guard",
    "register_public_locales_impact",
    "register_public_locales_limit",
    "register_resource_reference_handler",
    "register_seat_limit",
    "registered_commands",
]
