"""Public extension API of the Organizations module."""

from .canonical import canonical_json, canonical_json_hash
from .command_executor import (
    CHANNEL_FEATURES,
    CommandGate,
    Invocation,
    execute_plan,
    preview_plan,
    register_command_gate,
)
from .command_registry import (
    CommandSpec,
    Effect,
    Preview,
    UnknownCommand,
    command,
    command_for_tool,
    command_tools,
    register_command,
    registered_commands,
)
from .events import (
    DomainEvent,
    DomainEventDeliveryError,
    DomainEventHandler,
    dispatch_domain_event,
    register_domain_event_handler,
)
from .joining import (
    InvitationAcceptedHandler,
    SeatLimit,
    SeatLimitReached,
    register_invitation_accepted,
    register_seat_limit,
)
from .person_gate import PersonRequired, assert_person_required
from .public_locales import (
    LocaleRedirect,
    PublicLocalesLimit,
    include_site_source_locale,
    register_public_locales_changed,
    register_public_locales_guard,
    register_public_locales_impact,
    register_public_locales_limit,
)
from .references import (
    ResourceReferenceConflict,
    ResourceReferenceHandler,
    ResourceReferenceRejected,
    copy_resource_references,
    list_resource_reference_ids,
    record_resource_references,
    register_resource_reference_handler,
)
from .settings_commands import group_commands
from .settings_registry import SettingGroup, SettingSpec, register_setting_group, schema_entry
from .settings_service import (
    Resolved,
    change_settings,
    register_settings_feature_check,
    resolve,
    setting,
    settings_snapshot,
    validate_settings,
)

__all__ = [
    "Resolved",
    "SettingGroup",
    "SettingSpec",
    "change_settings",
    "group_commands",
    "register_setting_group",
    "register_settings_feature_check",
    "resolve",
    "setting",
    "settings_snapshot",
    "schema_entry",
    "validate_settings",
    "CHANNEL_FEATURES",
    "CommandGate",
    "CommandSpec",
    "DomainEvent",
    "DomainEventDeliveryError",
    "DomainEventHandler",
    "Effect",
    "InvitationAcceptedHandler",
    "LocaleRedirect",
    "Invocation",
    "Preview",
    "PersonRequired",
    "PublicLocalesLimit",
    "ResourceReferenceConflict",
    "ResourceReferenceHandler",
    "ResourceReferenceRejected",
    "SeatLimit",
    "SeatLimitReached",
    "UnknownCommand",
    "assert_person_required",
    "canonical_json",
    "canonical_json_hash",
    "command",
    "command_for_tool",
    "command_tools",
    "copy_resource_references",
    "include_site_source_locale",
    "execute_plan",
    "preview_plan",
    "dispatch_domain_event",
    "list_resource_reference_ids",
    "record_resource_references",
    "register_command",
    "register_command_gate",
    "register_domain_event_handler",
    "register_invitation_accepted",
    "register_public_locales_changed",
    "register_public_locales_guard",
    "register_public_locales_impact",
    "register_public_locales_limit",
    "register_resource_reference_handler",
    "register_seat_limit",
    "registered_commands",
]
