# Generated by Django 5.2.17 on 2026-10-03 10:05

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0059_inventory_audit_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("membership_id", models.UUIDField()),
                ("language", models.CharField(max_length=2)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AssistantTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("awaiting_consent", "Awaiting consent"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("steps_used", models.PositiveSmallIntegerField(default=0)),
                ("pending", models.JSONField(blank=True, null=True)),
                ("credit_reservation_key", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="assistant.assistantconversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("tool", "Tool")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("tool_call_id", models.CharField(blank=True, max_length=200)),
                ("result", models.JSONField(blank=True, null=True)),
                ("continuation", models.JSONField(blank=True, null=True)),
                ("usage_entry_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.assistantconversation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.assistantturn",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["organization", "membership_id", "-updated_at"],
                name="assistant_conv_person_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantconversation",
            constraint=models.UniqueConstraint(
                fields=("organization", "membership_id", "idempotency_key"),
                name="assistant_conv_key_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantturn",
            index=models.Index(fields=["state", "updated_at"], name="assistant_turn_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="assistantturn",
            constraint=models.UniqueConstraint(
                fields=("conversation", "index"), name="assistant_turn_index_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantturn",
            constraint=models.UniqueConstraint(
                fields=("conversation", "idempotency_key"), name="assistant_turn_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantturn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running", "awaiting_consent"])),
                fields=("conversation",),
                name="assistant_turn_one_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantturn",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "state__in",
                    ["queued", "running", "awaiting_consent", "done", "failed"],
                )),
                name="assistant_turn_state_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "index"), name="assistant_message_index_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assistantmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["user", "assistant", "tool"])),
                name="assistant_message_role_ck",
            ),
        ),
    ]
