# Generated by Django 5.2.17 on 2026-09-06 16:24

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0033_add_seo_permissions"),
        ("sites", "0026_merge_20260906_1804"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceSiteBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("external_project_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("root_url", models.URLField(max_length=2000)),
                ("remote_binding_id", models.UUIDField(blank=True, null=True)),
                ("remote_organization_id", models.UUIDField(blank=True, null=True)),
                ("remote_project_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="sites.site"),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("membership_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("requested_options", models.JSONField(default=dict)),
                ("effective_options", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("submitting", "Submitting"),
                            ("running", "Running"),
                            ("reconciling", "Reconciling"),
                            ("completed", "Completed"),
                            ("partial", "Partial without charge"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("remote_operation_id", models.UUIDField(blank=True, null=True)),
                ("remote_audit_run_id", models.UUIDField(blank=True, null=True)),
                ("remote_job_id", models.UUIDField(blank=True, null=True)),
                ("remote_module_run_id", models.UUIDField(blank=True, null=True)),
                ("credit_operation_key", models.CharField(max_length=120)),
                ("credit_reservation_key", models.CharField(blank=True, max_length=120)),
                ("credit_cost", models.PositiveIntegerField(default=0)),
                ("credit_state", models.CharField(default="free", max_length=16)),
                (
                    "provider_cost_usd",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("report_snapshot", models.JSONField(default=dict)),
                ("report_hash", models.CharField(blank=True, max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="seo.sourcesitebinding"
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditCallbackReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("event_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("remote_module_run_id", models.UUIDField()),
                ("remote_audit_run_id", models.UUIDField()),
                ("status", models.CharField(max_length=20)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="seo.auditorder"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_id", "event_id"),
                        name="seo_callback_org_source_event_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="sourcesitebinding",
            constraint=models.UniqueConstraint(
                fields=("organization", "site", "source_id"), name="seo_binding_org_site_source_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="auditorder",
            index=models.Index(
                fields=["organization", "state", "next_attempt_at"], name="seo_order_dispatch_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditorder",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="seo_order_org_key_uq"
            ),
        ),
    ]
