# Generated by Django 5.2.17 on 2026-10-02 19:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsageEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("call", "Wywołanie"), ("settlement", "Rozliczenie")],
                        default="call",
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("admitted", "Dopuszczone"),
                            ("calling", "W toku"),
                            ("done", "Zakończone"),
                            ("expired", "Wygasłe"),
                        ],
                        max_length=16,
                    ),
                ),
                ("task", models.CharField(max_length=80)),
                ("pool", models.CharField(max_length=32)),
                ("adapter", models.CharField(blank=True, max_length=32)),
                ("requested_model", models.CharField(blank=True, max_length=120)),
                ("resolved_model", models.CharField(blank=True, max_length=120)),
                ("resolved_provider", models.CharField(blank=True, max_length=80)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("purpose", models.CharField(max_length=16)),
                ("prompt_id", models.CharField(blank=True, max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("data_class", models.CharField(blank=True, max_length=24)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("resend_of", models.UUIDField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("finish_reason", models.CharField(blank=True, max_length=16)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("reasoning_tokens", models.PositiveIntegerField(default=0)),
                ("cached_input_tokens", models.PositiveIntegerField(default=0)),
                ("continuations_dropped", models.PositiveSmallIntegerField(default=0)),
                ("estimate_usd_micros", models.BigIntegerField(default=0)),
                ("cost_usd_micros", models.BigIntegerField(blank=True, null=True)),
                ("cost_source", models.CharField(blank=True, max_length=16)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                ("credits", models.PositiveIntegerField(blank=True, null=True)),
                ("units", models.PositiveIntegerField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "model_port_usageentry",
                "indexes": [
                    models.Index(fields=["pool", "created_at"], name="model_port_pool_created_idx"),
                    models.Index(
                        fields=["organization_id", "created_at"], name="model_port_org_created_idx"
                    ),
                    models.Index(
                        fields=["actor_id", "created_at"], name="model_port_actor_created_idx"
                    ),
                    models.Index(fields=["conversation_id"], name="model_port_conversation_idx"),
                    models.Index(fields=["reference"], name="model_port_reference_idx"),
                    models.Index(
                        condition=models.Q(("state__in", ["admitted", "calling"])),
                        fields=["state", "expires_at"],
                        name="model_port_open_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resend_of__isnull", False)),
                        fields=("resend_of",),
                        name="model_port_resend_once_uq",
                    )
                ],
            },
        ),
    ]
