# Generated by Django 5.2.17 on 2026-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model_port", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDoubleCompany",
            fields=[
                ("organization_id", models.UUIDField(primary_key=True, serialize=False)),
                ("added_by", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "model_port_testdoublecompany",
            },
        ),
    ]
