# Generated by Django 5.2.17 on 2026-08-11 10:21

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

CREATE_APPEND_ONLY_GUARDS = """
CREATE OR REPLACE FUNCTION sites_reject_append_only_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_pageversion_append_only
BEFORE UPDATE OR DELETE ON sites_pageversion
FOR EACH ROW EXECUTE FUNCTION sites_reject_append_only_mutation();

CREATE TRIGGER sites_pageblock_append_only
BEFORE UPDATE OR DELETE ON sites_pageblock
FOR EACH ROW EXECUTE FUNCTION sites_reject_append_only_mutation();

CREATE TRIGGER sites_publication_append_only
BEFORE UPDATE OR DELETE ON sites_publication
FOR EACH ROW EXECUTE FUNCTION sites_reject_append_only_mutation();
"""

DROP_APPEND_ONLY_GUARDS = """
DROP TRIGGER IF EXISTS sites_publication_append_only ON sites_publication;
DROP TRIGGER IF EXISTS sites_pageblock_append_only ON sites_pageblock;
DROP TRIGGER IF EXISTS sites_pageversion_append_only ON sites_pageversion;
DROP FUNCTION IF EXISTS sites_reject_append_only_mutation();
"""

CREATE_TENANT_LINK_GUARDS = """
CREATE OR REPLACE FUNCTION sites_validate_tenant_links()
RETURNS trigger AS $$
BEGIN
    IF TG_TABLE_NAME = 'sites_page' THEN
        IF (SELECT organization_id FROM sites_site WHERE id = NEW.site_id)
            IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'page site belongs to another organization' USING ERRCODE = '23514';
        END IF;
        IF NEW.current_draft_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM sites_pageversion
            WHERE id = NEW.current_draft_id
              AND page_id = NEW.id
              AND organization_id = NEW.organization_id
        ) THEN
            RAISE EXCEPTION 'current draft belongs to another page or organization'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'sites_pageversion' THEN
        IF (SELECT organization_id FROM sites_page WHERE id = NEW.page_id)
            IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'page version belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'sites_pageblock' THEN
        IF (SELECT organization_id FROM sites_pageversion WHERE id = NEW.page_version_id)
            IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'page block belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'sites_publication' THEN
        IF (SELECT organization_id FROM sites_site WHERE id = NEW.site_id)
            IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'publication belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.source_publication_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM sites_publication
            WHERE id = NEW.source_publication_id
              AND site_id = NEW.site_id
              AND organization_id = NEW.organization_id
        ) THEN
            RAISE EXCEPTION 'source publication belongs to another site or organization'
                USING ERRCODE = '23514';
        END IF;
    ELSIF TG_TABLE_NAME = 'sites_site' THEN
        IF NEW.current_publication_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM sites_publication
            WHERE id = NEW.current_publication_id
              AND site_id = NEW.id
              AND organization_id = NEW.organization_id
        ) THEN
            RAISE EXCEPTION 'current publication belongs to another site or organization'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_page_tenant_links
BEFORE INSERT OR UPDATE ON sites_page
FOR EACH ROW EXECUTE FUNCTION sites_validate_tenant_links();
CREATE TRIGGER sites_pageversion_tenant_links
BEFORE INSERT OR UPDATE ON sites_pageversion
FOR EACH ROW EXECUTE FUNCTION sites_validate_tenant_links();
CREATE TRIGGER sites_pageblock_tenant_links
BEFORE INSERT OR UPDATE ON sites_pageblock
FOR EACH ROW EXECUTE FUNCTION sites_validate_tenant_links();
CREATE TRIGGER sites_publication_tenant_links
BEFORE INSERT OR UPDATE ON sites_publication
FOR EACH ROW EXECUTE FUNCTION sites_validate_tenant_links();
CREATE TRIGGER sites_site_tenant_links
BEFORE INSERT OR UPDATE ON sites_site
FOR EACH ROW EXECUTE FUNCTION sites_validate_tenant_links();
"""

DROP_TENANT_LINK_GUARDS = """
DROP TRIGGER IF EXISTS sites_site_tenant_links ON sites_site;
DROP TRIGGER IF EXISTS sites_publication_tenant_links ON sites_publication;
DROP TRIGGER IF EXISTS sites_pageblock_tenant_links ON sites_pageblock;
DROP TRIGGER IF EXISTS sites_pageversion_tenant_links ON sites_pageversion;
DROP TRIGGER IF EXISTS sites_page_tenant_links ON sites_page;
DROP FUNCTION IF EXISTS sites_validate_tenant_links();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0013_add_sites_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('key', models.SlugField(max_length=80)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_site_pages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'site_id', 'key', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_page_versions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sites.page')),
            ],
            options={
                'ordering': ('organization_id', 'page_id', 'number'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('block_type', models.CharField(max_length=120)),
                ('schema_version', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('page_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='sites.pageversion')),
            ],
            options={
                'ordering': ('organization_id', 'page_version_id', 'position'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='current_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_pages', to='sites.pageversion'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('snapshot_schema_version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_site_publications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('source_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollbacks', to='sites.publication')),
            ],
            options={
                'ordering': ('organization_id', 'site_id', 'sequence'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80)),
                ('default_locale', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], default='pl', max_length=10)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
                ('current_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_sites', to='sites.publication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'slug', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='sites.site'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='pageversion',
            index=models.Index(fields=['organization', 'page', 'created_at'], name='sites_version_org_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(fields=('organization', 'page', 'number'), name='sites_version_org_page_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(fields=('organization', 'page', 'created_by', 'idempotency_key'), name='sites_version_org_page_actor_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='sites_version_number_positive_ck'),
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['organization', 'page_version', 'position'], name='sites_block_org_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageblock',
            constraint=models.UniqueConstraint(fields=('organization', 'page_version', 'position'), name='sites_block_org_version_position_uq'),
        ),
        migrations.AddConstraint(
            model_name='pageblock',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='sites_block_schema_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='pageblock',
            constraint=models.CheckConstraint(condition=models.Q(('block_type__regex', '^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$')), name='sites_block_type_format_ck'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'id'], name='sites_site_org_id_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'current_publication'], name='sites_site_org_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='sites_site_org_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'created_by', 'idempotency_key'), name='sites_site_org_actor_idem_uq'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['organization', 'site', 'created_at'], name='sites_publication_org_site_idx'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'sequence'), name='sites_publication_org_site_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'created_by', 'idempotency_key'), name='sites_publication_org_site_actor_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='sites_publication_sequence_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_schema_version__gte', 1)), name='sites_publication_schema_positive_ck'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['organization', 'site', 'id'], name='sites_page_org_site_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['organization', 'current_draft'], name='sites_page_org_draft_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'key'), name='sites_page_org_site_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'created_by', 'idempotency_key'), name='sites_page_org_site_actor_idem_uq'),
        ),
        migrations.RunSQL(CREATE_TENANT_LINK_GUARDS, reverse_sql=DROP_TENANT_LINK_GUARDS),
        migrations.RunSQL(CREATE_APPEND_ONLY_GUARDS, reverse_sql=DROP_APPEND_ONLY_GUARDS),
    ]
