# Generated by Django 5.2.17 on 2026-08-11 11:07

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

CREATE_TRANSLATION_GUARDS = """
CREATE OR REPLACE FUNCTION sites_validate_translation_links()
RETURNS trigger AS $$
BEGIN
    IF TG_TABLE_NAME = 'sites_pagetranslation' THEN
        IF NOT EXISTS (
            SELECT 1 FROM sites_page
            WHERE id = NEW.page_id
              AND site_id = NEW.site_id
              AND organization_id = NEW.organization_id
        ) THEN
            RAISE EXCEPTION 'translation page belongs to another site or organization'
                USING ERRCODE = '23514';
        END IF;
        IF (SELECT organization_id FROM sites_site WHERE id = NEW.site_id)
            IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'translation site belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
        IF NEW.locale = (SELECT default_locale FROM sites_site WHERE id = NEW.site_id)
            AND (
                NEW.allow_title_fallback
                OR NEW.allow_description_fallback
                OR NEW.allow_social_title_fallback
                OR NEW.allow_social_description_fallback
            ) THEN
            RAISE EXCEPTION 'base locale cannot use fallback' USING ERRCODE = '23514';
        END IF;
        IF TG_OP = 'UPDATE'
            AND OLD.slug_locked_at IS NOT NULL
            AND NEW.slug IS DISTINCT FROM OLD.slug THEN
            RAISE EXCEPTION 'published translation slug is locked' USING ERRCODE = '55000';
        END IF;
    ELSIF TG_TABLE_NAME = 'sites_pagetranslationmutation' THEN
        IF (SELECT organization_id FROM sites_pagetranslation WHERE id = NEW.translation_id)
            IS DISTINCT FROM NEW.organization_id THEN
            RAISE EXCEPTION 'translation mutation belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_pagetranslation_links
BEFORE INSERT OR UPDATE ON sites_pagetranslation
FOR EACH ROW EXECUTE FUNCTION sites_validate_translation_links();

CREATE TRIGGER sites_pagetranslationmutation_links
BEFORE INSERT OR UPDATE ON sites_pagetranslationmutation
FOR EACH ROW EXECUTE FUNCTION sites_validate_translation_links();

CREATE TRIGGER sites_pagetranslationmutation_append_only
BEFORE UPDATE OR DELETE ON sites_pagetranslationmutation
FOR EACH ROW EXECUTE FUNCTION sites_reject_append_only_mutation();
"""

DROP_TRANSLATION_GUARDS = """
DROP TRIGGER IF EXISTS sites_pagetranslationmutation_append_only
    ON sites_pagetranslationmutation;
DROP TRIGGER IF EXISTS sites_pagetranslationmutation_links
    ON sites_pagetranslationmutation;
DROP TRIGGER IF EXISTS sites_pagetranslation_links ON sites_pagetranslation;
DROP FUNCTION IF EXISTS sites_validate_translation_links();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_add_sites_role_permissions"),
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "locale",
                    models.CharField(choices=[("pl", "Polski"), ("en", "English")], max_length=10),
                ),
                ("slug", models.SlugField(max_length=80)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("description", models.CharField(blank=True, max_length=320)),
                ("social_title", models.CharField(blank=True, max_length=160)),
                ("social_description", models.CharField(blank=True, max_length=320)),
                ("allow_title_fallback", models.BooleanField(default=False)),
                ("allow_description_fallback", models.BooleanField(default=False)),
                ("allow_social_title_fallback", models.BooleanField(default=False)),
                ("allow_social_description_fallback", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("slug_locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="sites.page",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page_translations",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "site_id", "page_id", "locale"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PageTranslationMutation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("resulting_version", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_page_translation_mutations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mutations",
                        to="sites.pagetranslation",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "translation_id", "resulting_version"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="pagetranslation",
            index=models.Index(
                fields=["organization", "site", "locale", "slug"],
                name="sites_translation_route_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pagetranslation",
            index=models.Index(
                fields=["organization", "page", "locale"], name="sites_translation_page_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.UniqueConstraint(
                fields=("organization", "page", "locale"),
                name="sites_translation_org_page_locale_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.UniqueConstraint(
                fields=("organization", "site", "locale", "slug"),
                name="sites_translation_org_site_locale_slug_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="sites_translation_version_positive_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__in", ["pl", "en"])),
                name="sites_translation_locale_supported_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="pagetranslationmutation",
            index=models.Index(
                fields=["organization", "translation", "created_at"],
                name="sites_trmutation_org_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslationmutation",
            constraint=models.UniqueConstraint(
                fields=("organization", "translation", "created_by", "idempotency_key"),
                name="sites_trmutation_org_actor_idem_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslationmutation",
            constraint=models.UniqueConstraint(
                fields=("organization", "translation", "resulting_version"),
                name="sites_trmutation_org_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslationmutation",
            constraint=models.CheckConstraint(
                condition=models.Q(("resulting_version__gte", 1)),
                name="sites_trmutation_version_positive_ck",
            ),
        ),
        migrations.RunSQL(CREATE_TRANSLATION_GUARDS, reverse_sql=DROP_TRANSLATION_GUARDS),
    ]
