# Generated by Django 5.2.17 on 2026-08-11 17:16

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

CREATE_SITE_OUTBOX_GUARDS = """
ALTER TABLE sites_siteoutboxevent ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_siteoutboxevent FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_outbox_tenant_isolation ON sites_siteoutboxevent
USING (
    organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid
)
WITH CHECK (
    organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid
);

CREATE OR REPLACE FUNCTION sites_validate_outbox_event()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM sites_publication
        WHERE id = NEW.publication_id
          AND organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 'outbox publication belongs to another organization'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND (
        NEW.id IS DISTINCT FROM OLD.id
        OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.publication_id IS DISTINCT FROM OLD.publication_id
        OR NEW.event_type IS DISTINCT FROM OLD.event_type
        OR NEW.version IS DISTINCT FROM OLD.version
        OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
        OR NEW.correlation_id IS DISTINCT FROM OLD.correlation_id
        OR NEW.causation_id IS DISTINCT FROM OLD.causation_id
        OR NEW.payload IS DISTINCT FROM OLD.payload
        OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at
        OR (OLD.published_at IS NOT NULL AND NEW.published_at IS DISTINCT FROM OLD.published_at)
    ) THEN
        RAISE EXCEPTION 'outbox event payload is immutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_outbox_event_guard
BEFORE INSERT OR UPDATE ON sites_siteoutboxevent
FOR EACH ROW EXECUTE FUNCTION sites_validate_outbox_event();
"""

DROP_SITE_OUTBOX_GUARDS = """
DROP TRIGGER IF EXISTS sites_outbox_event_guard ON sites_siteoutboxevent;
DROP FUNCTION IF EXISTS sites_validate_outbox_event();
DROP POLICY IF EXISTS sites_outbox_tenant_isolation ON sites_siteoutboxevent;
ALTER TABLE sites_siteoutboxevent NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_siteoutboxevent DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_add_media_role_permissions"),
        ("sites", "0002_pagetranslation_pagetranslationmutation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteOutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                ("correlation_id", models.UUIDField()),
                ("causation_id", models.CharField(max_length=160)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_site_outbox_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "publication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_event",
                        to="sites.publication",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "occurred_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["organization", "published_at", "occurred_at"],
                        name="sites_outbox_pending_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="sites_outbox_version_positive_ck",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            CREATE_SITE_OUTBOX_GUARDS,
            reverse_sql=DROP_SITE_OUTBOX_GUARDS,
        ),
    ]
