# Generated by Django 5.2.17 on 2026-08-11 22:10

import hashlib
import uuid

import django.db.models.deletion
import django.db.models.manager
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils import timezone


def backfill_platform_domains(
    apps: Apps,
    _schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    site_model = apps.get_model('sites', 'Site')
    domain_model = apps.get_model('sites', 'Domain')
    platform_domain = settings.SITES_PLATFORM_DOMAIN.strip().lower().rstrip('.')
    now = timezone.now()
    for site in site_model.all_objects.order_by('id').iterator():
        readable_slug = site.slug[:50].rstrip('-')
        hostname = f"{readable_slug}-{site.id.hex[:12]}.{platform_domain}"
        domain_model.all_objects.get_or_create(
            site_id=site.id,
            kind='platform',
            defaults={
                'id': uuid.uuid7(),
                'organization_id': site.organization_id,
                'hostname': hostname,
                'status': 'verified',
                'verification_name': '',
                'verification_token': '',
                'tls_status': 'eligible',
                'is_canonical': True,
                'last_checked_at': now,
                'last_verified_at': now,
                'created_by_id': site.created_by_id,
                'idempotency_key': f"platform:backfill:{site.id}",
                'request_hash': hashlib.sha256(hostname.encode()).hexdigest(),
            },
        )


def remove_backfilled_platform_domains(
    apps: Apps,
    _schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    domain_model = apps.get_model('sites', 'Domain')
    domain_model.all_objects.filter(
        kind='platform',
        idempotency_key__startswith='platform:backfill:',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_add_media_role_permissions'),
        ('sites', '0003_siteoutboxevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=253)),
                ('kind', models.CharField(choices=[('platform', 'Subdomena platformy'), ('custom', 'Domena własna')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('verified', 'Zweryfikowana'), ('failed', 'Weryfikacja nieudana'), ('disabled', 'Wyłączona'), ('released', 'Zwolniona')], default='pending', max_length=16)),
                ('verification_name', models.CharField(max_length=253)),
                ('verification_token', models.CharField(max_length=320)),
                ('tls_status', models.CharField(choices=[('pending', 'Oczekuje'), ('eligible', 'Kwalifikuje się'), ('requested', 'Zażądano certyfikatu'), ('disabled', 'Wyłączony'), ('failed', 'Błąd')], default='pending', max_length=16)),
                ('is_canonical', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('dns_error_code', models.CharField(blank=True, max_length=40)),
                ('consecutive_transient_errors', models.PositiveIntegerField(default=0)),
                ('tls_last_requested_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_until', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_site_domains', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='sites.site')),
            ],
            options={
                'ordering': ('organization_id', 'site_id', 'hostname', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DomainMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_domain_mutations', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutations', to='sites.domain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'domain_id', 'created_at'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['hostname', 'status'], name='sites_domain_host_status_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status', 'next_check_at'], name='sites_domain_reverify_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organization', 'site', 'id'], name='sites_domain_org_site_idx'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'released'), _negated=True), fields=('hostname',), name='sites_domain_active_hostname_uq'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'platform'), models.Q(('status', 'released'), _negated=True)), fields=('site',), name='sites_domain_active_platform_uq'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical', True), models.Q(('status', 'released'), _negated=True)), fields=('site',), name='sites_domain_active_canonical_uq'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('organization', 'created_by', 'idempotency_key'), name='sites_domain_org_actor_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_canonical', False), ('quarantine_until__isnull', False), ('released_at__isnull', False), ('status', 'released')), models.Q(models.Q(('status', 'released'), _negated=True), ('quarantine_until__isnull', True), ('released_at__isnull', True)), _connector='OR'), name='sites_domain_release_state_ck'),
        ),
        migrations.AddIndex(
            model_name='domainmutation',
            index=models.Index(fields=['organization', 'domain', 'created_at'], name='sites_domainmutation_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainmutation',
            constraint=models.UniqueConstraint(fields=('organization', 'domain', 'created_by', 'action', 'idempotency_key'), name='sites_domainmutation_idem_uq'),
        ),
        migrations.RunPython(
            backfill_platform_domains,
            reverse_code=remove_backfilled_platform_domains,
        ),
    ]
