# Generated by Django 5.2.17 on 2026-08-25 19:32

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

CREATE_NAVIGATION_GUARDS = """
ALTER TABLE sites_navigationitem ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_navigationitem FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_navitem_tenant_isolation ON sites_navigationitem
USING (
    organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid
)
WITH CHECK (
    organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid
);

CREATE OR REPLACE FUNCTION sites_validate_navigation_item()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM sites_page
        WHERE id = NEW.page_id
          AND organization_id = NEW.organization_id
          AND site_id = NEW.site_id
    ) THEN
        RAISE EXCEPTION 'navigation item points at a page in another site or organization'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM sites_navigationitem
        WHERE id = NEW.parent_id
          AND organization_id = NEW.organization_id
          AND site_id = NEW.site_id
    ) THEN
        RAISE EXCEPTION 'navigation parent belongs to another site or organization'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_navigation_item_guard
BEFORE INSERT OR UPDATE ON sites_navigationitem
FOR EACH ROW EXECUTE FUNCTION sites_validate_navigation_item();
"""

DROP_NAVIGATION_GUARDS = """
DROP TRIGGER IF EXISTS sites_navigation_item_guard ON sites_navigationitem;
DROP FUNCTION IF EXISTS sites_validate_navigation_item();
DROP POLICY IF EXISTS sites_navitem_tenant_isolation ON sites_navigationitem;
ALTER TABLE sites_navigationitem NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_navigationitem DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organizationauditentry_action'),
        ('sites', '0005_site_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='navigation_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='sites.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sites.navigationitem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navigation_items', to='sites.site')),
            ],
            options={
                'ordering': ('organization_id', 'site_id', 'position', 'id'),
                'indexes': [models.Index(fields=['organization', 'site', 'position'], name='sites_navitem_org_site_pos_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'site', 'page'), name='sites_navitem_org_site_page_uq')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(
            CREATE_NAVIGATION_GUARDS,
            reverse_sql=DROP_NAVIGATION_GUARDS,
        ),
    ]
