# Generated by Django 5.2.17 on 2026-08-25 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_navigation_version_navigationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='automation_policy',
            field=models.CharField(choices=[('manual', 'Tylko ludzie'), ('automated', 'Automatyzacja treści')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='page',
            name='editing_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_site_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='editing_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
