# Generated by Django 5.2.17 on 2026-08-27 23:02

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

CREATE_COLLECTION_GUARDS = """
ALTER TABLE sites_contentcollection ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contentcollection FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_collection_tenant_isolation ON sites_contentcollection
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);

ALTER TABLE sites_contententry ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contententry FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_entry_tenant_isolation ON sites_contententry
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);

ALTER TABLE sites_contententryversion ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contententryversion FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_entryversion_tenant_isolation ON sites_contententryversion
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);

ALTER TABLE sites_contententrypublication ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contententrypublication FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_entrypub_tenant_isolation ON sites_contententrypublication
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);

CREATE OR REPLACE FUNCTION sites_validate_content_entry()
RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM sites_contentcollection
        WHERE id = NEW.collection_id
          AND organization_id = NEW.organization_id
          AND site_id = NEW.site_id
    ) THEN
        RAISE EXCEPTION 'content entry belongs to a collection in another site or organization'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_content_entry_guard
BEFORE INSERT OR UPDATE ON sites_contententry
FOR EACH ROW EXECUTE FUNCTION sites_validate_content_entry();

CREATE OR REPLACE FUNCTION sites_content_publication_is_immutable()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.id IS DISTINCT FROM OLD.id
        OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.entry_id IS DISTINCT FROM OLD.entry_id
        OR NEW.sequence IS DISTINCT FROM OLD.sequence
        OR NEW.snapshot::text IS DISTINCT FROM OLD.snapshot::text
        OR NEW.snapshot_hash IS DISTINCT FROM OLD.snapshot_hash
        OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
    ) THEN
        RAISE EXCEPTION 'content entry publication is append-only'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sites_content_publication_immutable
BEFORE UPDATE ON sites_contententrypublication
FOR EACH ROW EXECUTE FUNCTION sites_content_publication_is_immutable();
"""

DROP_COLLECTION_GUARDS = """
DROP TRIGGER IF EXISTS sites_content_publication_immutable ON sites_contententrypublication;
DROP FUNCTION IF EXISTS sites_content_publication_is_immutable();
DROP TRIGGER IF EXISTS sites_content_entry_guard ON sites_contententry;
DROP FUNCTION IF EXISTS sites_validate_content_entry();
DROP POLICY IF EXISTS sites_entrypub_tenant_isolation ON sites_contententrypublication;
DROP POLICY IF EXISTS sites_entryversion_tenant_isolation ON sites_contententryversion;
DROP POLICY IF EXISTS sites_entry_tenant_isolation ON sites_contententry;
DROP POLICY IF EXISTS sites_collection_tenant_isolation ON sites_contentcollection;
ALTER TABLE sites_contententrypublication NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_contententrypublication DISABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contententryversion NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_contententryversion DISABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contententry NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_contententry DISABLE ROW LEVEL SECURITY;
ALTER TABLE sites_contentcollection NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_contentcollection DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organizationauditentry_action'),
        ('sites', '0007_page_automation_policy_page_editing_locked_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('blog', 'Blog'), ('news', 'Aktualności'), ('guide', 'Poradniki')], default='blog', max_length=16)),
                ('base_path', models.SlugField(max_length=80)),
                ('automation_policy', models.CharField(choices=[('manual', 'Tylko ludzie'), ('automated', 'Automatyzacja treści')], default='manual', max_length=16)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_collections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_collections', to='sites.site')),
            ],
            options={
                'ordering': ('organization_id', 'site_id', 'key', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140)),
                ('locale', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('withdrawn', 'Wycofany')], default='draft', max_length=16)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('editing_locked_until', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='sites.contentcollection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_entries', to=settings.AUTH_USER_MODEL)),
                ('editing_locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_content_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_entries', to='sites.site')),
            ],
            options={
                'ordering': ('organization_id', 'collection_id', '-published_at', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentEntryPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_entry_publications', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='sites.contententry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'entry_id', 'sequence'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contententry',
            name='current_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_entries', to='sites.contententrypublication'),
        ),
        migrations.CreateModel(
            name='ContentEntryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('blocks', models.JSONField(default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_entry_versions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sites.contententry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'entry_id', 'number'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contententry',
            name='current_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_entries', to='sites.contententryversion'),
        ),
        migrations.AddIndex(
            model_name='contentcollection',
            index=models.Index(fields=['organization', 'site', 'id'], name='sites_collection_org_site_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentcollection',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'key'), name='sites_collection_org_site_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentcollection',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'base_path'), name='sites_collection_org_site_path_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentcollection',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'created_by', 'idempotency_key'), name='sites_collection_org_actor_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='contententrypublication',
            constraint=models.UniqueConstraint(fields=('organization', 'entry', 'sequence'), name='sites_entrypub_org_entry_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='contententrypublication',
            constraint=models.UniqueConstraint(fields=('organization', 'entry', 'created_by', 'idempotency_key'), name='sites_entrypub_org_actor_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='contententryversion',
            constraint=models.UniqueConstraint(fields=('organization', 'entry', 'number'), name='sites_entryversion_org_entry_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='contententryversion',
            constraint=models.UniqueConstraint(fields=('organization', 'entry', 'created_by', 'idempotency_key'), name='sites_entryversion_org_actor_idem_uq'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['organization', 'collection', 'state', '-published_at'], name='sites_entry_index_idx'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.UniqueConstraint(fields=('organization', 'collection', 'locale', 'slug'), name='sites_entry_org_coll_locale_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.UniqueConstraint(fields=('organization', 'collection', 'created_by', 'idempotency_key'), name='sites_entry_org_coll_actor_idem_uq'),
        ),
        migrations.RunSQL(
            CREATE_COLLECTION_GUARDS,
            reverse_sql=DROP_COLLECTION_GUARDS,
        ),
    ]
