# Generated by Django 5.2.17 on 2026-08-28 07:31

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organizationauditentry_action'),
        ('sites', '0009_content_rls_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAutomationGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.UUIDField()),
                ('mode', models.CharField(choices=[('suggest_only', 'Tylko propozycje'), ('draft_write', 'Zapis draftu'), ('publish_with_approval', 'Publikacja po akceptacji'), ('autonomous', 'Autonomiczna publikacja')], default='suggest_only', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_grants', to='sites.contentcollection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_automation_grants', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_grants', to='sites.site')),
            ],
            options={
                'ordering': ('organization_id', 'credential_id', 'id'),
                'indexes': [models.Index(fields=['organization', 'credential_id'], name='sites_grant_org_credential_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('collection__isnull', True), ('site__isnull', False)), models.Q(('collection__isnull', False), ('site__isnull', True)), _connector='OR'), name='sites_grant_exactly_one_target_ck')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
