# Generated by Django 5.2.17 on 2026-08-28 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_site_redirect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='schedule_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='schedule_state',
            field=models.CharField(choices=[('none', 'Bez planu'), ('pending', 'Zaplanowana'), ('cancelled', 'Anulowana'), ('failed', 'Nieudana')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='contententry',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_content_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contententry',
            name='scheduled_membership_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contententry',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteoutboxevent',
            name='entry_publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_event', to='sites.contententrypublication'),
        ),
        migrations.AlterField(
            model_name='siteoutboxevent',
            name='publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_event', to='sites.publication'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['schedule_state', 'scheduled_publish_at'], name='sites_entry_due_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schedule_state', 'pending'), _negated=True), models.Q(('scheduled_membership_id__isnull', False), ('scheduled_publish_at__isnull', False)), _connector='OR'), name='sites_entry_pending_schedule_complete_ck'),
        ),
        migrations.AddConstraint(
            model_name='siteoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_publication__isnull', True), ('publication__isnull', False)), models.Q(('entry_publication__isnull', False), ('publication__isnull', True)), _connector='OR'), name='sites_outbox_exactly_one_subject_ck'),
        ),
    ]
