# Generated by Django 5.2.17 on 2026-08-29 09:47

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_platform_workspace'),
        ('sites', '0017_outbox_entry_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_tags', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='sites.site')),
            ],
            options={
                'ordering': ('organization_id', 'site_id', 'slug'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentEntryTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='sites.contententry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_links', to='sites.contenttag')),
            ],
            options={
                'ordering': ('organization_id', 'entry_id', 'tag_id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='contenttag',
            index=models.Index(fields=['organization', 'site', 'slug'], name='sites_tag_org_site_idx'),
        ),
        migrations.AddConstraint(
            model_name='contenttag',
            constraint=models.UniqueConstraint(fields=('organization', 'site', 'slug'), name='sites_tag_org_site_slug_uq'),
        ),
        migrations.AddIndex(
            model_name='contententrytag',
            index=models.Index(fields=['organization', 'tag', 'entry'], name='sites_entry_tag_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='contententrytag',
            constraint=models.UniqueConstraint(fields=('organization', 'entry', 'tag'), name='sites_entry_tag_org_entry_tag_uq'),
        ),
    ]
