# Generated by Django 5.2.17 on 2026-08-29 10:33

from typing import Any

from django.conf import settings
from django.db import migrations, models


def demote_unbounded_autonomy(_apps: Any, schema_editor: Any) -> None:
    """An autonomous grant that never carried bounds must not survive as one.

    Inventing limits for it would be inventing policy nobody agreed to, so the
    grant drops to `suggest_only`: the automation keeps reading and loses the
    right to publish until an operator re-issues it with explicit bounds. That
    is the correct outcome for a grant that was unbounded in the first place.

    Written as SQL rather than through the ORM: this model's managers are
    tenant-scoped, and a historical model has no tenant context to scope by.
    """
    schema_editor.execute(
        """
        UPDATE sites_contentautomationgrant
        SET mode = 'suggest_only'
        WHERE mode = 'autonomous'
          AND (
            max_changes_per_day IS NULL
            OR max_payload_bytes IS NULL
            OR expires_at IS NULL
          )
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_platform_workspace'),
        ('sites', '0019_content_tag_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentautomationgrant',
            name='allowed_link_hosts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentautomationgrant',
            name='max_changes_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentautomationgrant',
            name='max_payload_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentautomationgrant',
            name='window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentautomationgrant',
            name='window_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            demote_unbounded_autonomy,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='contentautomationgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'autonomous'), _negated=True), models.Q(('expires_at__isnull', False), ('max_changes_per_day__isnull', False), ('max_payload_bytes__isnull', False)), _connector='OR'), name='sites_grant_autonomous_bounded_ck'),
        ),
        migrations.AddConstraint(
            model_name='contentautomationgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('window_end__isnull', True), ('window_start__isnull', True)), models.Q(('window_end__isnull', False), ('window_start__isnull', False)), _connector='OR'), name='sites_grant_window_complete_ck'),
        ),
    ]
