# Generated by Django 5.2.17 on 2026-08-30 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_platform_workspace'),
        ('sites', '0020_grant_bounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siteoutboxevent',
            name='sites_outbox_exactly_one_subject_ck',
        ),
        migrations.AddConstraint(
            model_name='siteoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('publication__isnull', True), ('entry_publication__isnull', True), _connector='OR'), name='sites_outbox_at_most_one_subject_ck'),
        ),
    ]
