# Generated by Django 5.2.17 on 2026-08-30 09:11

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_platform_workspace'),
        ('sites', '0021_outbox_subject_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=32)),
                ('resource_id', models.UUIDField()),
                ('version', models.PositiveBigIntegerField()),
                ('credential_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('risk', models.CharField(max_length=16)),
                ('expected_outcome', models.TextField(blank=True)),
                ('sources', models.JSONField(default=list)),
                ('commands', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', '-created_at', 'id'),
                'indexes': [models.Index(fields=['organization', 'resource_type', 'resource_id'], name='sites_proposal_resource_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'resource_type', 'resource_id', 'version'), name='sites_proposal_org_resource_version_uq')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
