# Generated by Django 5.2.17 on 2026-09-06 15:50

from typing import Any

from django.db import migrations, models


def preserve_review_history(apps: Any, schema_editor: Any) -> None:
    proposal = apps.get_model('sites', 'ContentProposal')
    rows = proposal.objects.using(schema_editor.connection.alias)
    if rows.exclude(metadata_before={}).exists() or rows.exclude(review_state='pending').exists():
        raise RuntimeError(
            'Proposal review history exists; retain the expanded schema during application rollback.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0024_private_tables_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentproposal',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentproposal',
            name='decision_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentproposal',
            name='metadata_after',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contentproposal',
            name='metadata_before',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contentproposal',
            name='metadata_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentproposal',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='contentproposal',
            name='target',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(migrations.RunPython.noop, preserve_review_history),
    ]
