# Generated by Django 5.2.17 on 2026-09-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0025_append_only_allows_erasure'),
        ('sites', '0025_proposal_metadata_review'),
    ]

    operations = [
    ]
