# Generated by Django 5.2.17 on 2026-09-06 17:08

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0033_add_seo_permissions"),
        ("sites", "0026_merge_20260906_1804"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintImportReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("credential_id", models.UUIDField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="sites.page"),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.contentproposal"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="sites.site"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "site",
                            "created_by",
                            "credential_id",
                            "idempotency_key",
                        ),
                        name="sites_blueprint_delivery_uq",
                        nulls_distinct=False,
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
