# Generated by Django 5.2.17 on 2026-09-20 12:36

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

CREATE = """
ALTER TABLE sites_siteappearancerevision ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_siteappearancerevision FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_appearance_tenant ON sites_siteappearancerevision
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
CREATE FUNCTION sites_guard_appearance() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.organization_id = NULLIF(current_setting('app.erasing_organization_id', true), '')::uuid THEN
            RETURN OLD;
        END IF;
        RAISE EXCEPTION 'Appearance revision requires tenant erasure' USING ERRCODE = '55000';
    ELSIF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Appearance revision is immutable' USING ERRCODE = '55000';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM sites_site WHERE id = NEW.site_id AND organization_id = NEW.organization_id) THEN
        RAISE EXCEPTION 'Appearance site tenant mismatch' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER sites_appearance_guard BEFORE INSERT OR UPDATE OR DELETE
ON sites_siteappearancerevision FOR EACH ROW EXECUTE FUNCTION sites_guard_appearance();
"""
DROP = """
DROP TRIGGER sites_appearance_guard ON sites_siteappearancerevision;
DROP FUNCTION sites_guard_appearance();
DROP POLICY sites_appearance_tenant ON sites_siteappearancerevision;
ALTER TABLE sites_siteappearancerevision NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_siteappearancerevision DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0040_audit_farm_share_actions"),
        ("sites", "0028_blueprint_receipt_isolation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAppearanceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveBigIntegerField()),
                ("data", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appearance_revisions",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ("-number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "site", "number"),
                        name="sites_appearance_version_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "site", "created_by", "idempotency_key"),
                        name="sites_appearance_idem_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number__gte", 1)), name="sites_appearance_number_ck"
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(CREATE, reverse_sql=DROP),
    ]
