# Generated by Django 5.2.17 on 2026-09-21 08:35

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

FORWARD_SQL = """
ALTER TABLE sites_siteinquiry ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_siteinquiry FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_inquiry_tenant ON sites_siteinquiry
USING (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid);

CREATE FUNCTION sites_inquiry_tenant_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sites_site WHERE id = NEW.site_id
                   AND organization_id = NEW.organization_id)
       OR NOT EXISTS (SELECT 1 FROM sites_publication WHERE id = NEW.publication_id
                      AND site_id = NEW.site_id AND organization_id = NEW.organization_id)
       OR (NEW.notification_message_id IS NOT NULL AND NOT EXISTS (
           SELECT 1 FROM notifications_notificationmessage
           WHERE id = NEW.notification_message_id AND organization_id = NEW.organization_id
       )) THEN
        RAISE EXCEPTION 'Site inquiry references another tenant or site' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER sites_inquiry_tenant_guard BEFORE INSERT OR UPDATE ON sites_siteinquiry
FOR EACH ROW EXECUTE FUNCTION sites_inquiry_tenant_guard();
"""

REVERSE_SQL = """
DROP TRIGGER sites_inquiry_tenant_guard ON sites_siteinquiry;
DROP FUNCTION sites_inquiry_tenant_guard();
DROP POLICY sites_inquiry_tenant ON sites_siteinquiry;
ALTER TABLE sites_siteinquiry NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_siteinquiry DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_message_attachment"),
        ("sites", "0029_site_appearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("page_path", models.CharField(max_length=500)),
                ("block_position", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("message", models.TextField(max_length=5000)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("request_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="notifications.notificationmessage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.publication"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inquiries",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "indexes": [
                    models.Index(
                        fields=["organization", "site", "-id"], name="sites_inquiry_inbox_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "site", "idempotency_key"),
                        name="sites_inquiry_idempotency_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
