# Generated by Django 5.2.17 on 2026-09-28 13:55

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

# Own templates (F4-B) are tenant data: forced row-level security on both
# tables, a version that must belong to its template's organization, and
# versions append-only like page versions (the shared function lets tenant
# erasure through, ADR-042).
RLS = """
ALTER TABLE sites_sitetemplate ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_sitetemplate FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_sitetemplate_tenant ON sites_sitetemplate
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);

ALTER TABLE sites_sitetemplateversion ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_sitetemplateversion FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_sitetemplateversion_tenant ON sites_sitetemplateversion
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);

CREATE FUNCTION sites_template_version_tenant_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sites_sitetemplate WHERE id = NEW.template_id
                   AND organization_id = NEW.organization_id) THEN
        RAISE EXCEPTION 'Template version references another tenant''s template'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER sites_template_version_tenant_guard BEFORE INSERT
ON sites_sitetemplateversion FOR EACH ROW EXECUTE FUNCTION sites_template_version_tenant_guard();
CREATE TRIGGER sites_template_version_append_only BEFORE UPDATE OR DELETE
ON sites_sitetemplateversion FOR EACH ROW EXECUTE FUNCTION sites_reject_append_only_mutation();
"""
DROP_RLS = """
DROP TRIGGER sites_template_version_append_only ON sites_sitetemplateversion;
DROP TRIGGER sites_template_version_tenant_guard ON sites_sitetemplateversion;
DROP FUNCTION sites_template_version_tenant_guard();
DROP POLICY sites_sitetemplateversion_tenant ON sites_sitetemplateversion;
ALTER TABLE sites_sitetemplateversion NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_sitetemplateversion DISABLE ROW LEVEL SECURITY;
DROP POLICY sites_sitetemplate_tenant ON sites_sitetemplate;
ALTER TABLE sites_sitetemplate NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_sitetemplate DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0051_audit_crews_teams'),
        ('sites', '0037_page_version_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('section', 'Sekcja'), ('page', 'Strona')], max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'kind', 'name'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('blocks', models.JSONField(default=list)),
                ('page_presentation', models.JSONField(blank=True, default=None, null=True)),
                ('media_asset_ids', models.JSONField(default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('source_page_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sites.sitetemplate')),
            ],
            options={
                'ordering': ('organization_id', 'template_id', 'number'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sitetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'kind', 'name'), name='sites_template_org_kind_name_uq'),
        ),
        migrations.AddConstraint(
            model_name='sitetemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'created_by', 'idempotency_key'), name='sites_template_org_actor_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='sitetemplateversion',
            constraint=models.UniqueConstraint(fields=('organization', 'template', 'number'), name='sites_template_version_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='sitetemplateversion',
            constraint=models.UniqueConstraint(fields=('organization', 'template', 'created_by', 'idempotency_key'), name='sites_template_version_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='sitetemplateversion',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='sites_template_version_number_ck'),
        ),
        migrations.RunSQL(RLS, DROP_RLS),
    ]
