# Generated by Django 5.2.17 on 2026-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0040_page_locale_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("publish", "Publikacja"),
                    ("rollback", "Przywrócenie"),
                    ("page_delete", "Usunięcie podstrony"),
                    ("locale_accept", "Akceptacja tłumaczenia"),
                    ("locale_publish", "Publikacja wersji językowej"),
                    ("locale_withdraw", "Zdjęcie wersji językowej"),
                    ("translation_job", "Tłumaczenie automatyczne"),
                    ("translation_revert", "Cofnięcie tłumaczenia"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
