# Generated by Django 5.2.17 on 2026-10-02 18:27

from typing import Any

from django.conf import settings
from django.db import migrations, models

# ADR-071 pkt 3: content languages are registry codes checked by shape, not a
# pl/en list. Walking back re-adds the pl/en check on page translations, which
# cannot hold once a company has written another language — the walk back stops
# with a count instead of deleting customers' translations on its own.


def refuse_walking_back_over_other_languages(apps: Any, schema_editor: Any) -> None:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT locale, count(*) FROM sites_pagetranslation "
            "WHERE locale NOT IN ('pl', 'en') GROUP BY locale ORDER BY locale"
        )
        rows = cursor.fetchall()
    if rows:
        counts = ", ".join(f"{locale}: {count}" for locale, count in rows)
        raise RuntimeError(
            "Cofnięcie sites 0043 przywraca listę pl/en, a są tłumaczenia stron w innych "
            f"językach ({counts}). Usuń je albo zmień świadomie, potem cofnij ponownie."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0053_organization_public_locales"),
        ("sites", "0042_public_locales_from_sites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pagetranslation",
            name="sites_translation_locale_supported_ck",
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_walking_back_over_other_languages),
        migrations.AlterField(
            model_name="contententry",
            name="locale",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="pagetranslation",
            name="locale",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="site",
            name="default_locale",
            field=models.CharField(default="pl", max_length=10),
        ),
        migrations.AlterField(
            model_name="siteonboardingdraft",
            name="default_locale",
            field=models.CharField(default="pl", max_length=10),
        ),
        migrations.AddConstraint(
            model_name="contententry",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="sites_entry_locale_format_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="sites_translation_locale_format_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_locale__regex", "^[a-z]{2}$")),
                name="sites_site_locale_format_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="siteonboardingdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_locale__regex", "^[a-z]{2}$")),
                name="sites_onboarding_locale_format_ck",
            ),
        ),
    ]
