# Generated by Django 5.2.17 on 2026-10-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0043_content_locale_strings"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetranslation",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
