# Generated by Django 5.2.17 on 2026-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0044_translation_withdrawn_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviewday',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='siteinquiry',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
