# Generated by Django 5.2.17 on 2026-10-02 23:49

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

# A receipt of the translation engine's write: read and written inside the
# tenant, so forced row-level security like every private tenant table.
FORWARD_SQL = """
ALTER TABLE sites_pagetranslationwrite ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_pagetranslationwrite FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_pagetranslationwrite_tenant_isolation ON sites_pagetranslationwrite
USING (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid);
"""

REVERSE_SQL = """
DROP POLICY sites_pagetranslationwrite_tenant_isolation ON sites_pagetranslationwrite;
ALTER TABLE sites_pagetranslationwrite NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_pagetranslationwrite DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0056_organization_settings"),
        ("sites", "0045_inquiry_and_view_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTranslationWrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("job_ref", models.CharField(blank=True, default="", max_length=160)),
                ("outcomes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.page",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "page", "locale", "idempotency_key"),
                        name="sites_translationwrite_idem_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
