# Generated by Django 5.2.17 on 2026-10-03 00:53

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

# The receipt of the translation engine's write of an article: read and written
# inside the tenant, so forced row-level security like every private tenant table.
FORWARD_SQL = """
ALTER TABLE sites_entrytranslationwrite ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites_entrytranslationwrite FORCE ROW LEVEL SECURITY;
CREATE POLICY sites_entrytranslationwrite_tenant_isolation ON sites_entrytranslationwrite
USING (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid);
"""

REVERSE_SQL = """
DROP POLICY sites_entrytranslationwrite_tenant_isolation ON sites_entrytranslationwrite;
ALTER TABLE sites_entrytranslationwrite NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sites_entrytranslationwrite DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0056_organization_settings"),
        ("sites", "0046_translation_write"),
    ]

    operations = [
        migrations.AddField(
            model_name="contententry",
            name="pending_reason",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="contententry",
            name="pending_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.contententryversion",
            ),
        ),
        migrations.AddField(
            model_name="contententry",
            name="translation_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.contententry",
            ),
        ),
        migrations.AddField(
            model_name="contententryversion",
            name="origin",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="contententryversion",
            name="origin_ref",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="contententryversion",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.contententryversion",
            ),
        ),
        migrations.AddField(
            model_name="contententryversion",
            name="source_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.contententryversion",
            ),
        ),
        migrations.AddField(
            model_name="contententryversion",
            name="units",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagelocaleversion",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.pagelocaleversion",
            ),
        ),
        migrations.CreateModel(
            name="EntryTranslationWrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("job_ref", models.CharField(blank=True, default="", max_length=160)),
                ("outcomes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.contententry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "entry", "locale", "idempotency_key"),
                        name="sites_entrytranslationwrite_idem_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
