# Generated by Django 5.2.17 on 2026-10-03 02:49

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

# A site's texts in other languages and the receipts of their translation
# writes: read and written inside the tenant, so forced row-level security like
# every private tenant table.
TABLES = ("sites_sitetexttranslation", "sites_sitetextwrite")
FORWARD_SQL = "\n".join(
    f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
CREATE POLICY {table}_tenant_isolation ON {table}
USING (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = nullif(current_setting('app.organization_id', true), '')::uuid);
"""
    for table in TABLES
)
REVERSE_SQL = "\n".join(
    f"""
DROP POLICY {table}_tenant_isolation ON {table};
ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;
"""
    for table in TABLES
)


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0057_alter_organizationauditentry_action"),
        ("sites", "0047_entry_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTextTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("source_hash", models.CharField(max_length=64)),
                ("source_text", models.TextField()),
                ("anchor", models.CharField(max_length=160)),
                ("text", models.TextField(blank=True, default="")),
                ("provenance", models.JSONField(blank=True, null=True)),
                ("origin_ref", models.CharField(blank=True, default="", max_length=160)),
                ("previous_text", models.TextField(blank=True, default="")),
                ("previous_provenance", models.JSONField(blank=True, null=True)),
                ("pending_text", models.TextField(blank=True, default="")),
                ("pending_provenance", models.JSONField(blank=True, null=True)),
                ("pending_reason", models.CharField(blank=True, default="", max_length=40)),
                ("pending_ref", models.CharField(blank=True, default="", max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "site", "locale", "anchor"],
                        name="sites_sitetext_anchor_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "site", "locale", "source_hash"),
                        name="sites_sitetext_hash_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                        name="sites_sitetext_locale_format_ck",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SiteTextWrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("locale", models.CharField(max_length=10)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("job_ref", models.CharField(blank=True, default="", max_length=160)),
                ("outcomes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "site", "locale", "idempotency_key"),
                        name="sites_sitetextwrite_idem_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
