# Generated by Django 5.2.17 on 2026-10-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0048_site_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='accepted_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.contententryversion'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='body_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.pagelocaleversion'),
        ),
    ]
