# Generated by Django 5.2.17 on 2026-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0049_accepted_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinquiry",
            name="erased_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
