# Generated by Django 5.2.17 on 2026-08-11 23:48

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0016_alter_organizationauditentry_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderMessageRoute",
            fields=[
                (
                    "provider_message_id",
                    models.CharField(max_length=160, primary_key=True, serialize=False),
                ),
                ("organization_id", models.UUIDField()),
                ("message_id", models.UUIDField(unique=True)),
                ("tenant_context_ciphertext", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("prefix", models.CharField(max_length=20, unique=True)),
                ("secret_hash", models.CharField(max_length=256)),
                ("scopes", models.JSONField(default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "rotated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="notifications.apikey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_hash", models.CharField(max_length=64)),
                ("template_key", models.CharField(max_length=100)),
                ("template_version", models.PositiveIntegerField(default=1)),
                (
                    "locale",
                    models.CharField(choices=[("pl", "Polski"), ("en", "English")], max_length=10),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("required", "Wymagana"), ("marketing", "Marketingowa")],
                        max_length=16,
                    ),
                ),
                ("context", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Oczekuje"),
                            ("processing", "Przetwarzana"),
                            ("sent", "Wysłana"),
                            ("delivered", "Dostarczona"),
                            ("bounced", "Odrzucona"),
                            ("complained", "Zgłoszona"),
                            ("suppressed", "Wstrzymana"),
                            ("dead_letter", "Dead letter"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=160)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("correlation_id", models.UUIDField()),
                ("causation_id", models.CharField(max_length=160)),
                ("signed_tenant_context", models.TextField()),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("retention_expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-created_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("outcome", models.CharField(max_length=32)),
                ("provider_request_id", models.CharField(blank=True, max_length=160)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="notifications.notificationmessage",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "locale",
                    models.CharField(choices=[("pl", "Polski"), ("en", "English")], max_length=10),
                ),
                ("marketing_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProviderEventInbox",
            fields=[
                ("event_id", models.CharField(max_length=160, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20)),
                ("payload_digest", models.CharField(max_length=64)),
                ("provider_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="notifications.providermessageroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=120)),
                ("event_version", models.PositiveIntegerField(default=1)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Oczekuje"),
                            ("processing", "Przetwarzana"),
                            ("sent", "Wysłana"),
                            ("delivered", "Dostarczona"),
                            ("bounced", "Odrzucona"),
                            ("complained", "Zgłoszona"),
                            ("suppressed", "Wstrzymana"),
                            ("dead_letter", "Dead letter"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("signed_tenant_context", models.TextField()),
                ("correlation_id", models.UUIDField()),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=8)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebhookAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_digest", models.CharField(blank=True, max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="notifications.webhookdelivery",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=2048)),
                ("signing_secret_ciphertext", models.TextField()),
                ("secret_hint", models.CharField(max_length=8)),
                ("events", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="notifications.webhookendpoint",
            ),
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Oczekuje"),
                            ("processing", "Przetwarzany"),
                            ("ready", "Gotowy"),
                            ("expired", "Wygasł"),
                            ("dead_letter", "Dead letter"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(default=dict)),
                ("content", models.TextField(blank=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("signed_tenant_context", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "created_by", "idempotency_key"),
                        name="notifications_export_org_actor_idem_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("recipient_hash", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=24)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("organization", "recipient_hash"),
                        name="notifications_suppression_active_uq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(
                fields=["organization", "status", "next_attempt_at"],
                name="notifications_message_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationmessage",
            index=models.Index(
                fields=["provider_message_id"], name="notifications_provider_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationmessage",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="notifications_message_org_idem_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1), ("template_version__gte", 1)),
                name="notifications_message_limits_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationattempt",
            constraint=models.UniqueConstraint(
                fields=("message", "number"), name="notifications_attempt_no_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="notifications_pref_org_user_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookattempt",
            constraint=models.UniqueConstraint(
                fields=("delivery", "number"), name="notifications_webhook_attempt_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["organization", "status", "next_attempt_at"],
                name="notifications_webhook_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookdelivery",
            constraint=models.UniqueConstraint(
                fields=("endpoint", "event_id"), name="notifications_webhook_event_uq"
            ),
        ),
    ]
