# Generated by Django 5.2.17 on 2026-08-11 23:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rls_and_tenant_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTaskRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("object_key", models.CharField(max_length=160)),
                ("tenant_context_ciphertext", models.TextField()),
                ("next_dispatch_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "object_key"), name="notifications_pending_route_uq"
                    )
                ],
            },
        ),
    ]
