# Generated by Django 5.2.17 on 2026-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_pendingtaskroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKeyCredentialRoute",
            fields=[
                ("prefix", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("api_key_id", models.UUIDField(unique=True)),
                ("organization_id", models.UUIDField()),
                ("secret_hash", models.CharField(max_length=256)),
                ("scopes", models.JSONField(default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
