# Generated by Django 5.2.17 on 2026-09-05 07:05

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

TABLE = "notifications_appnotification"
POLICY = f"{TABLE}_tenant_isolation"

# ADR-039: a tenant table is guarded by the database unless its module declares
# it public, and an inbox is nobody's business but its own organization's.
ENABLE_RLS = f"""
ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY;
CREATE POLICY {POLICY} ON {TABLE}
USING (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('app.organization_id', true), '')::uuid);
"""

DISABLE_RLS = f"""
DROP POLICY IF EXISTS {POLICY} ON {TABLE};
ALTER TABLE {TABLE} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {TABLE} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_apikeycredentialroute'),
        ('organizations', '0024_alter_organizationauditentry_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('info', 'Informacja'), ('warning', 'Ostrzeżenie'), ('critical', 'Pilne')], default='info', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'user', 'read_at'], name='notif_app_org_user_read_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'idempotency_key'), name='notifications_app_org_user_idem_uq')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
            migrations.RunSQL(ENABLE_RLS, DISABLE_RLS),
    ]
