# Generated by Django 5.2.17 on 2026-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_app_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationmessage",
            name="attachment_ref",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
