# Generated by Django 5.2.17 on 2026-10-02 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_message_attachment"),
        ("organizations", "0053_organization_public_locales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmessage",
            name="locale",
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name="notificationmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("locale__regex", "^[a-z]{2}$")),
                name="notifications_message_locale_format_ck",
            ),
        ),
    ]
