# Generated by Django 5.2.17 on 2026-10-04 00:27

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0004_grant_role_permissions"),
        ("organizations", "0059_inventory_audit_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=32)),
                ("source", models.CharField(max_length=64)),
                ("buyer_name", models.CharField(max_length=160)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                ("buyer_phone", models.CharField(blank=True, max_length=40)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amounts",
                    models.CharField(choices=[("gross", "Brutto"), ("net", "Netto")], max_length=8),
                ),
                ("net_minor", models.BigIntegerField(default=0)),
                ("vat_minor", models.BigIntegerField(default=0)),
                ("gross_minor", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("awaiting_payment", "Do zapłaty"),
                            ("partially_paid", "Opłacone częściowo"),
                            ("paid", "Opłacone"),
                            ("fulfilled", "Zrealizowane"),
                            ("completed", "Zakończone"),
                            ("canceled", "Anulowane"),
                            ("refunded", "Zwrócone"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("company_site", "Strona firmy"),
                            ("catalog", "Katalog"),
                            ("office", "Biuro"),
                        ],
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("version", models.PositiveIntegerField(default=1)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "-placed_at", "-id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrderCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prefix", models.CharField(max_length=8)),
                ("year", models.PositiveSmallIntegerField()),
                ("last", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking", "Rezerwacja"),
                            ("product", "Produkt"),
                            ("extra", "Dodatek"),
                            ("discount", "Rabat"),
                            ("voucher", "Bon"),
                            ("delivery", "Dostawa"),
                            ("fee", "Opłata"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("customer_name", models.CharField(max_length=240)),
                ("quantity", models.IntegerField()),
                ("unit_amount_minor", models.BigIntegerField()),
                ("net_minor", models.BigIntegerField()),
                ("vat_minor", models.BigIntegerField()),
                ("gross_minor", models.BigIntegerField()),
                (
                    "tax_rate",
                    models.CharField(
                        choices=[
                            ("23", "23%"),
                            ("8", "8%"),
                            ("5", "5%"),
                            ("0", "0%"),
                            ("zw", "zw."),
                            ("np", "np."),
                        ],
                        max_length=4,
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("source_reference", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="commerce.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("order_id", "revision", "position"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization", "-placed_at"], name="commerce_order_placed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization", "customer"], name="commerce_order_customer_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("organization", "number"),
                name="commerce_order_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordercounter",
            constraint=models.UniqueConstraint(
                fields=("organization", "prefix", "year"), name="commerce_ordercounter_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="orderline",
            index=models.Index(
                fields=["organization", "source", "source_reference"],
                name="commerce_orderline_source_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderline",
            constraint=models.UniqueConstraint(
                fields=("order", "revision", "position"), name="commerce_orderline_position_uq"
            ),
        ),
    ]
