# Generated by Django 5.2.17 on 2026-10-04 01:15

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_publish_commerce_feature"),
        ("organizations", "0059_inventory_audit_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "Przedpłata"),
                            ("balance", "Dopłata"),
                            ("full", "Całość"),
                            ("security_deposit", "Kaucja"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("transfer", "Przelew"),
                            ("cash", "Na miejscu"),
                            ("cash_on_delivery", "Za pobraniem"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment", "Czeka na wpłatę"),
                            ("processing", "W toku"),
                            ("authorized", "Zablokowana"),
                            ("succeeded", "Wpłacona"),
                            ("failed", "Nieudana"),
                            ("canceled", "Wycofana"),
                            ("expired", "Wygasła"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("recorded_by", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="commerce.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("order_id", "created_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("charge", "Wpłata"),
                            ("provider_fee", "Opłata operatora"),
                            ("application_fee", "Prowizja platformy"),
                            ("refund", "Zwrot"),
                            ("refund_fee_reversal", "Zwrot prowizji"),
                            ("dispute_hold", "Blokada sporu"),
                            ("dispute_release", "Zwolnienie sporu"),
                            ("dispute_fee", "Opłata za spór"),
                            ("payout", "Wypłata"),
                            ("security_received", "Kaucja przyjęta"),
                            ("security_returned", "Kaucja zwrócona"),
                            ("security_retained", "Kaucja zatrzymana"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger",
                        to="commerce.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger",
                        to="commerce.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("order_id", "occurred_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["organization", "order"], name="commerce_payment_order_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["organization", "order"], name="commerce_ledger_order_idx"),
        ),
    ]
