# Generated by Django 5.2.17 on 2026-10-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0007_grant_payment_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRoute",
            fields=[
                ("payment_id", models.UUIDField(primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField()),
                ("signed_tenant_context", models.TextField()),
                ("due_at", models.DateTimeField()),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("dispatched_at__isnull", True)),
                        fields=["due_at"],
                        name="commerce_payroute_due_idx",
                    )
                ],
            },
        ),
    ]
