# Generated by Django 5.2.17 on 2026-10-04 04:19

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0008_payment_route"),
        ("organizations", "0059_inventory_audit_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_due_minor",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("transfer", "Przelew"),
                            ("cash", "Na miejscu"),
                            ("cash_on_delivery", "Za pobraniem"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Zwrócono"), ("canceled", "Wycofany")], max_length=24
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("refunded_at", models.DateTimeField()),
                ("recorded_by", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="commerce.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("order_id", "created_at", "id"),
                "indexes": [
                    models.Index(fields=["organization", "order"], name="commerce_refund_order_idx")
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
