# Generated by Django 5.2.17 on 2026-09-21 07:28

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0042_audit_herd_pushed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('block', 'Klocek'), ('dressing', 'Opatrunek'), ('medicine', 'Lek'), ('tool', 'Narzędzie'), ('other', 'Inne')], default='other', max_length=16)),
                ('unit', models.CharField(choices=[('piece', 'Sztuka'), ('pack', 'Opakowanie'), ('ml', 'Mililitr'), ('g', 'Gram'), ('m', 'Metr')], default='piece', max_length=8)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_cost_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'name', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ('organization_id', 'item_id', 'holder_id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('receipt', 'Przyjęcie'), ('issue', 'Wydanie pracownikowi'), ('return', 'Zwrot do magazynu'), ('consumption', 'Zużycie przy pracy'), ('adjustment', 'Korekta stanu')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost_minor', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', '-created_at', 'id'),
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='inventory_item_org_name_uq'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 0)), name='inventory_item_minimum_not_negative_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('organization', 'item', 'holder'), name='inventory_balance_item_holder_uq', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'item'], name='inventory_movement_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inventory_movement_quantity_ck'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source', ''), _negated=True), fields=('organization', 'source', 'source_reference', 'item', 'holder'), name='inventory_movement_source_uq', nulls_distinct=False),
        ),
    ]
