# Generated by Django 5.2.17 on 2026-09-23 18:55

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_clear_v1_stock"),
        ("organizations", "0047_audit_inventory_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PZ", "Przyjęcie zewnętrzne"),
                            ("WZ", "Wydanie zewnętrzne"),
                            ("RW", "Rozchód wewnętrzny"),
                            ("PW", "Przychód wewnętrzny"),
                            ("MM", "Przesunięcie międzymagazynowe"),
                            ("INW", "Inwentaryzacja"),
                        ],
                        max_length=3,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("last", models.PositiveIntegerField(default=0)),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("organization_id", "name", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PZ", "Przyjęcie zewnętrzne"),
                            ("WZ", "Wydanie zewnętrzne"),
                            ("RW", "Rozchód wewnętrzny"),
                            ("PW", "Przychód wewnętrzny"),
                            ("MM", "Przesunięcie międzymagazynowe"),
                            ("INW", "Inwentaryzacja"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Szkic"), ("posted", "Zatwierdzony")],
                        default="draft",
                        max_length=8,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=32)),
                ("document_date", models.DateField()),
                ("counterparty", models.CharField(blank=True, max_length=160)),
                ("source", models.CharField(blank=True, max_length=40)),
                ("source_reference", models.CharField(blank=True, max_length=64)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("organization_id", "-document_date", "-created_at", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockDocumentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price_minor", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "ordering": ("document_id", "position"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("warehouse", "Magazyn"), ("person", "Zapas osoby")], max_length=16
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("organization_id", "kind", "name", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("source", models.CharField(max_length=40)),
                ("source_reference", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktywna"),
                            ("consumed", "Zużyta"),
                            ("released", "Zwolniona"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("tax_id", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("organization_id", "name", "id"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="inventorybalance",
            options={"ordering": ("organization_id", "item_id", "location_id")},
        ),
        migrations.RemoveConstraint(
            model_name="inventorybalance",
            name="inventory_balance_item_holder_uq",
        ),
        migrations.RemoveConstraint(
            model_name="inventorymovement",
            name="inventory_movement_source_uq",
        ),
        migrations.RemoveField(
            model_name="inventorybalance",
            name="holder",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="holder",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="note",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="source",
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="source_reference",
        ),
        migrations.AddField(
            model_name="inventorybalance",
            name="reserved",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="ean",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sale_price_net_minor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="system_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="vat_rate",
            field=models.CharField(
                choices=[("23", "23%"), ("8", "8%"), ("5", "5%"), ("0", "0%"), ("zw", "zw.")],
                default="23",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="inventorybalance",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="minimum_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "Sztuka"),
                    ("pack", "Opakowanie"),
                    ("ml", "Mililitr"),
                    ("l", "Litr"),
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("m", "Metr"),
                    ("hour", "Godzina"),
                ],
                default="piece",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PZ", "Przyjęcie zewnętrzne"),
                    ("WZ", "Wydanie zewnętrzne"),
                    ("RW", "Rozchód wewnętrzny"),
                    ("PW", "Przychód wewnętrzny"),
                    ("MM", "Przesunięcie międzymagazynowe"),
                    ("INW", "Inwentaryzacja"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AddField(
            model_name="documentsequence",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="inventorycategory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.inventorycategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("organization", "sku"),
                name="inventory_item_sku_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_key", ""), _negated=True),
                fields=("organization", "system_key"),
                name="inventory_item_system_key_uq",
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="corrects",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction",
                to="inventory.stockdocument",
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.stockdocument",
            ),
        ),
        migrations.AddField(
            model_name="stockdocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory.stockdocument",
            ),
        ),
        migrations.AddField(
            model_name="stockdocumentline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="stockdocumentline",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="holder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="source_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="target_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="inventorybalance",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balances",
                to="inventory.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.stocklocation",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["organization", "location"], name="inventory_movement_place_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorybalance",
            constraint=models.UniqueConstraint(
                fields=("organization", "item", "location"), name="inventory_balance_location_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorybalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__gte", 0)), name="inventory_balance_reserved_ck"
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="stockdocument",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="inventory.supplier",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind", "year"), name="inventory_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "key"), name="inventory_category_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="inventory_category_name_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdocumentline",
            constraint=models.UniqueConstraint(
                fields=("document", "position"), name="inventory_line_position_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="inventory_line_quantity_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("holder__isnull", False)),
                fields=("organization", "holder"),
                name="inventory_location_holder_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="inventory_location_default_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("holder__isnull", False), ("is_default", False), ("kind", "person")),
                    models.Q(("holder__isnull", True), ("kind", "warehouse")),
                    _connector="OR",
                ),
                name="inventory_location_kind_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "source", "source_reference", "item", "location"),
                name="inventory_reservation_source_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="inventory_reservation_quantity_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="inventory_supplier_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="stockdocument",
            index=models.Index(
                fields=["organization", "kind", "status"], name="inventory_document_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("organization", "number"),
                name="inventory_document_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("source", ""), _negated=True), ("corrects__isnull", True)
                ),
                fields=("organization", "kind", "source", "source_reference"),
                name="inventory_document_source_uq",
            ),
        ),
    ]
