# Generated by Django 5.2.17 on 2026-09-25 07:49

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_grant_inventory_use"),
        ("organizations", "0048_audit_visit_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="tracks_lots",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InventoryLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "item_id", "expires_on", "number"),
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.inventorylot",
            ),
        ),
        migrations.AddField(
            model_name="stockdocumentline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.inventorylot",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["organization", "item", "location"], name="inventory_movement_stock_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorylot",
            constraint=models.UniqueConstraint(
                fields=("organization", "item", "number"), name="inventory_lot_number_uq"
            ),
        ),
    ]
